<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class DataDitraTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = '{
            "array": [
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-02-12T00:00:00",
                    "MES ": "FEBRERO",
                    "DIA": "DOMINGO",
                    "HORA": "00:45:00",
                    "RANGO_HORA": "00:00  a 02:59",
                    "SECCIONAL": "DEATA",
                    "COORDENADAS": "10.404072, -74.850773",
                    "ADSCRITO": "DEATA",
                    "IDENTIFICACION": 72284897,
                    "GRADO": "SI",
                    "NOMBRES": "JUAN MANUEL",
                    "APELLIDOS": "ARTEAGA MARTINEZ",
                    "EDAD": 39,
                    "RANGO DE EDAD ": "38-42",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "UNION LIBRE",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "NO",
                    "PLACA": "NGC98F",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2021,
                    "CC": 124,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "SI",
                    "RTM": "SI",
                    "LICENCIA": "SI",
                    "TIPO": "CHOQUE",
                    "HIPOTESIS": "DEJAR O MOVILIZAR SEMOVIENTES EN LA VIA",
                    "POSIBLE_OCURRENCIA ": "CHOQUE  CON SEMOVIENTE "
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-02-23T00:00:00",
                    "MES ": "FEBRERO",
                    "DIA": "JUEVES",
                    "HORA": "00:45:00",
                    "RANGO_HORA": "00:00  a 02:59",
                    "SECCIONAL": "MESAN",
                    "COORDENADAS": "10.981385, -74.312682",
                    "ADSCRITO": "DEATA",
                    "IDENTIFICACION": 1082408034,
                    "GRADO": "PT",
                    "NOMBRES": "YOSMI YESITH",
                    "APELLIDOS": "FERNANDEZ MONTENEGRO",
                    "EDAD": 31,
                    "RANGO DE EDAD ": "28-32",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "UNION LIBRE",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "NO",
                    "PLACA": "AEG21E",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2016,
                    "CC": 321,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "NO",
                    "RTM": "NO",
                    "LICENCIA": "NO",
                    "TIPO": "CHOQUE",
                    "HIPOTESIS": "POR ESTABLECER",
                    "POSIBLE_OCURRENCIA ": " SON CHOCADOS POR UN VEHICULO FANTASMA QUE SE DIO A LA HUIDA "
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-05-26T00:00:00",
                    "MES ": "MAYO",
                    "DIA": "VIERNES",
                    "HORA": "01:30:00",
                    "RANGO_HORA": "00:00  a 02:59",
                    "SECCIONAL": "MEVAL",
                    "COORDENADAS": "6.265206, -75.572160",
                    "ADSCRITO": "MEVAL",
                    "IDENTIFICACION": 1036338434,
                    "GRADO": "PT",
                    "NOMBRES": "SOL MAYRA",
                    "APELLIDOS": "RODRIGUEZ VASQUEZ",
                    "EDAD": 29,
                    "RANGO DE EDAD ": "28-32",
                    "GENERO": "FEMENINO",
                    "ESTADO CIVIL": "SOLTERO",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "SI",
                    "PLACA": "AQO86G",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2022,
                    "CC": 650,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "SI",
                    "RTM": "SI",
                    "LICENCIA": "SI",
                    "TIPO": "CHOQUE",
                    "HIPOTESIS": "PERDIDA DEL CONTROL DEL VEHICULO",
                    "POSIBLE_OCURRENCIA ": "COLISIONA CON OBJETO FIJO (VEHICULO DE SECRETARIA DE MOVILIDAD, QUE REALIZABA CIERRE DE VIA POR INUNDACION)"
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-02-18T00:00:00",
                    "MES ": "FEBRERO",
                    "DIA": "SABADO",
                    "HORA": "01:51:00",
                    "RANGO_HORA": "00:00  a 02:59",
                    "SECCIONAL": "MEBOG",
                    "COORDENADAS": "4.576147, -74.088981",
                    "ADSCRITO": "MEBOG",
                    "IDENTIFICACION": 1023928221,
                    "GRADO": "PT",
                    "NOMBRES": "RAFAEL ALFONSO",
                    "APELLIDOS": "ROMERO ESCOBAR",
                    "EDAD": 29,
                    "RANGO DE EDAD ": "28-32",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "SIN INFORMACION",
                    "EMBRIAGUEZ": "SI",
                    "RESPONSABILIDAD": "SI",
                    "PLACA": "WAX91A",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2008,
                    "CC": 644,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "SI",
                    "RTM": "SI",
                    "LICENCIA": "SI",
                    "TIPO": "CHOQUE",
                    "HIPOTESIS": "TRANSITAR EN CONTRAVIA",
                    "POSIBLE_OCURRENCIA ": "SE MOVILIZABA LA MOTOPXCICLETA EN SENTIDO CONTRARIO"
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-02-02T00:00:00",
                    "MES ": "FEBRERO",
                    "DIA": "JUEVES",
                    "HORA": "02:20:00",
                    "RANGO_HORA": "00:00  a 02:59",
                    "SECCIONAL": "MECUC",
                    "COORDENADAS": "7.926251, -72.484207",
                    "ADSCRITO": "DEVAU",
                    "IDENTIFICACION": 1090417658,
                    "GRADO": "PT",
                    "NOMBRES": "DARWIN",
                    "APELLIDOS": "HERRERA REYES",
                    "EDAD": 32,
                    "RANGO DE EDAD ": "28-32",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "SIN INFORMACION",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "SI",
                    "PLACA": "QCV33F",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2022,
                    "CC": 125,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "NO",
                    "RTM": "N/A",
                    "LICENCIA": "SI",
                    "TIPO": "VOLCAMIENTO LATERAL",
                    "HIPOTESIS": "PERDIDA DEL CONTROL DEL VEHICULO",
                    "POSIBLE_OCURRENCIA ": "PERDIDA DE CONTROL DEL VEHICULO"
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-06-05T00:00:00",
                    "MES ": "JUNIO",
                    "DIA": "LUNES",
                    "HORA": "02:38:00",
                    "RANGO_HORA": "00:00  a 02:59",
                    "SECCIONAL": "MEBOG",
                    "COORDENADAS": "4.589241, -74.108990",
                    "ADSCRITO": "MEBOG",
                    "IDENTIFICACION": 1030702637,
                    "GRADO": "PT",
                    "NOMBRES": "LAURA CAMILA",
                    "APELLIDOS": "OSSA VELEZ",
                    "EDAD": 23,
                    "RANGO DE EDAD ": "23-27",
                    "GENERO": "FEMENINO",
                    "ESTADO CIVIL": "SOLTERO",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "SI",
                    "PLACA": "BQR04G",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2023,
                    "CC": 175,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "NO",
                    "RTM": "N/A",
                    "LICENCIA": "SI",
                    "TIPO": "CHOQUE CON OBJETO FIJO",
                    "HIPOTESIS": "PERDIDA DEL CONTROL DEL VEHICULO",
                    "POSIBLE_OCURRENCIA ": "COLISION CON VALLAS DE PUBLICIDAD"
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-02-19T00:00:00",
                    "MES ": "FEBRERO",
                    "DIA": "DOMINGO",
                    "HORA": "03:00:00",
                    "RANGO_HORA": "03:00 a 05:59",
                    "SECCIONAL": "MEMOT",
                    "COORDENADAS": "8.906855, -75805743",
                    "ADSCRITO": "MEMOT",
                    "IDENTIFICACION": 1085099280,
                    "GRADO": "PT",
                    "NOMBRES": "JANIS",
                    "APELLIDOS": "ROJAS ARRIETA",
                    "EDAD": 31,
                    "RANGO DE EDAD ": "28-32",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "SIN INFORMACION",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "NO",
                    "PLACA": "TJQ76C",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2014,
                    "CC": 153,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "NO",
                    "RTM": "NO",
                    "LICENCIA": "SI",
                    "TIPO": "CHOQUE",
                    "HIPOTESIS": "TRANSITAR EN CONTRAVIA",
                    "POSIBLE_OCURRENCIA ": "MOTOCICLETA DEL PARTICULAR INVADE CARRIL "
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-07-15T00:00:00",
                    "MES ": "JULIO",
                    "DIA": "SABADO",
                    "HORA": "03:30:00",
                    "RANGO_HORA": "03:00 a 05:59",
                    "SECCIONAL": "REMSA",
                    "COORDENADAS": "4.854835, -74.068563",
                    "ADSCRITO": "DINAE",
                    "IDENTIFICACION": 1085304258,
                    "GRADO": "PT",
                    "NOMBRES": "JESSICA ALEXANDRA ",
                    "APELLIDOS": "LOPEZ MONTENEGRO",
                    "EDAD": 30,
                    "RANGO DE EDAD ": "28-32",
                    "GENERO": "FEMENINO",
                    "ESTADO CIVIL": "SOLTERO",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "SI",
                    "PLACA": "PTX27D",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2015,
                    "CC": 125,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "SI",
                    "RTM": "SI",
                    "LICENCIA": "NO",
                    "TIPO": "VOLCAMIENTO LATERAL",
                    "HIPOTESIS": "PERDIDA DEL CONTROL DEL VEHICULO",
                    "POSIBLE_OCURRENCIA ": "NO REGISTRA"
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-07-02T00:00:00",
                    "MES ": "JULIO",
                    "DIA": "DOMINGO",
                    "HORA": "03:45:00",
                    "RANGO_HORA": "03:00 a 05:59",
                    "SECCIONAL": "DEVAL",
                    "COORDENADAS": "3.528482,-76.277329",
                    "ADSCRITO": "DEVAL",
                    "IDENTIFICACION": 1112968535,
                    "GRADO": "PT",
                    "NOMBRES": "FABIAN STIVEN",
                    "APELLIDOS": "BERRIO RENGIFO",
                    "EDAD": 27,
                    "RANGO DE EDAD ": "23-27",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "SOLTERO",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "POR ESTABLECER",
                    "PLACA": "BHQ09G",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2023,
                    "CC": 250,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "SI",
                    "RTM": "N/A",
                    "LICENCIA": "SI",
                    "TIPO": "CHOQUE CON OBJETO FIJO",
                    "HIPOTESIS": "PERDIDA DEL CONTROL DEL VEHICULO",
                    "POSIBLE_OCURRENCIA ": "CHOQUE CON OBJETO FIJO (POSTE ALUMBRADO PUBLICO) TRANSITA CON ACOMPANANTE Y FALLECEN LOS DOS EN EL SITIO"
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-04-16T00:00:00",
                    "MES ": "ABRIL",
                    "DIA": "DOMINGO",
                    "HORA": "04:00:00",
                    "RANGO_HORA": "03:00 a 05:59",
                    "SECCIONAL": "DEVAL",
                    "COORDENADAS": " 4.084260, -76.197099",
                    "ADSCRITO": "DEQUI",
                    "IDENTIFICACION": 1116241209,
                    "GRADO": "PT",
                    "NOMBRES": "CARLOS HUMBERTO ",
                    "APELLIDOS": "RAMIREZ BENAVIDEZ ",
                    "EDAD": 34,
                    "RANGO DE EDAD ": "33-37",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "SIN INFORMACION",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "NO",
                    "PLACA": "UCN15D",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2020,
                    "CC": 114,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "NO",
                    "RTM": "NO",
                    "LICENCIA": "SI",
                    "TIPO": "CHOQUE",
                    "HIPOTESIS": "POR ESTABLECER",
                    "POSIBLE_OCURRENCIA ": "FUE COLISIONADO POR VEHICULO DESCONOCIDO POR LA PARTE POSTERIOR Y EMPRENDE LA HUIDA, NO HACE PRESENCIA GUARDAS DE TRANSITO "
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-06-22T00:00:00",
                    "MES ": "JUNIO",
                    "DIA": "JUEVES",
                    "HORA": "05:15:00",
                    "RANGO_HORA": "03:00 a 05:59",
                    "SECCIONAL": "DECUN",
                    "COORDENADAS": "4.585324, -74.207240",
                    "ADSCRITO": "ESJIM",
                    "IDENTIFICACION": 1014227017,
                    "GRADO": "PT",
                    "NOMBRES": "CHRISTIAN CAMILO ",
                    "APELLIDOS": "GOMEZ QUICENO  ",
                    "EDAD": 31,
                    "RANGO DE EDAD ": "28-33",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "SOLTERO",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "SI",
                    "PLACA": "QPN-15F  ",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2022,
                    "CC": 373,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "SI",
                    "RTM": "SI",
                    "LICENCIA": "SI",
                    "TIPO": "CHOQUE CON OBJETO FIJO",
                    "HIPOTESIS": "CHOQUE CON OBJETO FIJO (SARDINEL)",
                    "POSIBLE_OCURRENCIA ": "MICROSUENO- PIERDER EL CONTROL DE LA MOTOCICLETA COLISIONANDO CONTRA EL SEPARADOR DE LA CALZADA DE TRANSMILENIO "
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-09-24T00:00:00",
                    "MES ": "SEPTIEMBRE",
                    "DIA": "DOMINGO",
                    "HORA": "05:15:00",
                    "RANGO_HORA": "03:00 a 05:59",
                    "SECCIONAL": "METIB",
                    "COORDENADAS": "9.393409, -75.434101",
                    "ADSCRITO": "METIB",
                    "IDENTIFICACION": 1110546874,
                    "GRADO": "PT",
                    "NOMBRES": "JHOAN EDILBER ",
                    "APELLIDOS": "GOMEZ POLANIA",
                    "EDAD": 28,
                    "RANGO DE EDAD ": "23-28",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "SOLTERO",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "POR ESTABLECER",
                    "PLACA": "ZGZ13E",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": "N/A",
                    "CC": "N/A",
                    "CLASE_S": "OFICIAL",
                    "SOAT": "SI",
                    "RTM": "SI",
                    "LICENCIA": "SI",
                    "TIPO": "CHOQUE",
                    "HIPOTESIS": null,
                    "POSIBLE_OCURRENCIA ": "COLISIONANDO CON UNA MOTOCICLETA PARTICULAR, LOS LESIONADOS FUERON REMITIDOS A LA CLINICA ASOTRAUMA, DONDE VALORACION MEDICA EL UNIFORMADO PRESENTO HEMATOMAS EN EL ROSTRO Y PARTE POSTERIOR DEL CRANEO, PRACTICANDOLE TUBO TRAQUEOTOMIA Y LOS CIVILES LACERACIONES MULTIPLES Y CONTUSIONES (LEVES).\nEL 151023, EL POLICIAL FUE DADO DE ALTA SIENDO TRASLADADO A SU LUGAR DE RESIDENCIA, SALE CON 30 DIAS DE EXCUSA MEDICA, DONDE CONTINUO CON LAS TERAPIAS Y ATENCION MEDICA POR PARTE DE SANIDAD.\nEL 281123 EL UNIFORMADO INGRESO A LA CLINICA ASOTRAUMA, PARA CONTROL MEDICO DONDE QUEDO HOSPITALIZADO 07 DIAS, DONDE LE REALIZARON EXAMENES MEDICOS.\nEL 081223 EL UNIFORMADO PRESENTO FUERTE DOLOR DE CABEZA, SIENDO TRASLADADO A LA CLINICA ASOTRAUMA, DONDE LE REALIZAN INTERVENCION QUIRURGICA EN EL CEREBRO.\nEL 101223 A LAS 10:00 HORAS SE PRESENTO EL DECESO. SEGUN EPICRISIS HABRIA PRESENTADO HEMORRAGIA INTRACEREBRAL."
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-03-12T00:00:00",
                    "MES ": "MARZO",
                    "DIA": "DOMINGO",
                    "HORA": "05:40:00",
                    "RANGO_HORA": "03:00 a 05:59",
                    "SECCIONAL": "DESUC",
                    "COORDENADAS": "9.481353, -75.506861",
                    "ADSCRITO": "DESUC",
                    "IDENTIFICACION": 92558856,
                    "GRADO": "IT",
                    "NOMBRES": "MIGUEL JOSE",
                    "APELLIDOS": "VIDES HERAZO",
                    "EDAD": 43,
                    "RANGO DE EDAD ": "43-47",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "SIN INFORMACION",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "NO",
                    "PLACA": "KFR655",
                    "CLASE_V": "PASAJERO",
                    "MODELO": null,
                    "CC": "N/A",
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "N/A",
                    "RTM": "N/A",
                    "LICENCIA": "N/A",
                    "TIPO": "CHOQUE CON OBJETO FIJO",
                    "HIPOTESIS": "PERDIDA DEL CONTROL DEL VEHICULO",
                    "POSIBLE_OCURRENCIA ": "PERDIDA DEL CONTROL DEL VEHICULO"
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-06-18T00:00:00",
                    "MES ": "JUNIO",
                    "DIA": "DOMINGO",
                    "HORA": "05:45:00",
                    "RANGO_HORA": "03:00 a 05:59",
                    "SECCIONAL": "DECAU",
                    "COORDENADAS": " 3.012264, -76.484005",
                    "ADSCRITO": "DECAU",
                    "IDENTIFICACION": 1007616046,
                    "GRADO": "PT",
                    "NOMBRES": "NIVER ENRIQUE ",
                    "APELLIDOS": "RANGEL RODRIGUEZ",
                    "EDAD": 22,
                    "RANGO DE EDAD ": "33-37",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "UNION LIBRE",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "SI",
                    "PLACA": "SIA79F",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2022,
                    "CC": 249,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "SI",
                    "RTM": "SI",
                    "LICENCIA": "SI",
                    "TIPO": "CHOQUE CON OBJETO FIJO",
                    "HIPOTESIS": "CHOQUE CON OBJETO FIJO (SARDINEL)",
                    "POSIBLE_OCURRENCIA ": "MANIFIESTAN QUE ESTE SE ENCONTRABA CONSUMIENDO BEBIDAS ALCOHOLICAS EN UN ESTABLECIMIENTO ABIERTO AL PUBLICO, LUEGO SE DIRIGIO A UNA VIA PRINCIPAL A CONTINUAR CON LA ACTIVIDAD Y POSTERIORMENTE SE RETIRA DEL LUGAR MOVILIZANDOSE EN SU MOTOCICLETA."
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-06-25T00:00:00",
                    "MES ": "JUNIO",
                    "DIA": "DOMINGO",
                    "HORA": "05:55:00",
                    "RANGO_HORA": "03:00 a 05:59",
                    "SECCIONAL": "DECES",
                    "COORDENADAS": "10.017715, -73.906780",
                    "ADSCRITO": "DECES",
                    "IDENTIFICACION": 72268510,
                    "GRADO": "SI",
                    "NOMBRES": "JOSE MARIA",
                    "APELLIDOS": "PRENTT SILVERA ",
                    "EDAD": 41,
                    "RANGO DE EDAD ": "38-42",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "SOLTERO",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "SI",
                    "PLACA": "MUL098",
                    "CLASE_V": "AUTOMOVIL",
                    "MODELO": 2014,
                    "CC": 1999,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "SI",
                    "RTM": "SI",
                    "LICENCIA": "SI",
                    "TIPO": "VOLCAMIENTO LATERAL",
                    "HIPOTESIS": "PERDIDA DEL CONTROL DEL VEHICULO",
                    "POSIBLE_OCURRENCIA ": "PERDIDA DEL CONTROL DEL VEHICULO- SALIRSE DE LA CALZADA"
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-01-13T00:00:00",
                    "MES ": "ENERO",
                    "DIA": "VIERNES",
                    "HORA": "06:00:00",
                    "RANGO_HORA": "06:00 a 08:59",
                    "SECCIONAL": "MEBOG",
                    "COORDENADAS": "4.680921, -74.104988",
                    "ADSCRITO": "MEBOG",
                    "IDENTIFICACION": 1003048410,
                    "GRADO": "PT",
                    "NOMBRES": "ALDAIR",
                    "APELLIDOS": "CONTRERA REGINO",
                    "EDAD": 20,
                    "RANGO DE EDAD ": "18-22",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "SOLTERO",
                    "EMBRIAGUEZ": "SI",
                    "RESPONSABILIDAD": "SI",
                    "PLACA": "SIN65E",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2019,
                    "CC": 199,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "SI",
                    "RTM": "SI",
                    "LICENCIA": "SI",
                    "TIPO": "CHOQUE",
                    "HIPOTESIS": "EMBRIAGUEZ APARENTE",
                    "POSIBLE_OCURRENCIA ": "122 - GIRAR BRUSCAMENTE PARA EL VEHICULO FURGON Y 114 - EMBRIAGUEZ APARENTE PARA LA MOTOCICLETA"
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-12-23T00:00:00",
                    "MES ": "DICIEMBRE",
                    "DIA": "SABADO",
                    "HORA": "07:00:00",
                    "RANGO_HORA": "06:00 a 08:59",
                    "SECCIONAL": "DESAN",
                    "COORDENADAS": "4.680921, -74.104988",
                    "ADSCRITO": "DEMAM",
                    "IDENTIFICACION": 13929934,
                    "GRADO": "PT",
                    "NOMBRES": "ALBERT",
                    "APELLIDOS": "FLOREZ AGUDELO",
                    "EDAD": 40,
                    "RANGO DE EDAD ": "38-42",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "SOLTERO",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "POR ESTABLECER",
                    "PLACA": "PYG51F",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2021,
                    "CC": 100,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "SI",
                    "RTM": "SI",
                    "LICENCIA": "SI",
                    "TIPO": "CHOQUE CON OBJETO FIJO",
                    "HIPOTESIS": "MICRO SUENO",
                    "POSIBLE_OCURRENCIA ": "PERDIDA DEL CONTROL DE LA MOTOCICLETA Y COLISIONA CON OBEJTO FIJO (ARBOL)"
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-02-24T00:00:00",
                    "MES ": "FEBRERO",
                    "DIA": "VIERNES",
                    "HORA": "08:00:00",
                    "RANGO_HORA": "06:00 a 08:59",
                    "SECCIONAL": "DETOL",
                    "COORDENADAS": "4.144427, -74881820",
                    "ADSCRITO": "DETOL",
                    "IDENTIFICACION": 1007443140,
                    "GRADO": "PT",
                    "NOMBRES": "ANDRES",
                    "APELLIDOS": "PRADA CALDERON",
                    "EDAD": 21,
                    "RANGO DE EDAD ": "18-22",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "SIN INFORMACION",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "POR ESTABLECER",
                    "PLACA": "MYY90G",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2023,
                    "CC": 249,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "SI",
                    "RTM": "N/A",
                    "LICENCIA": "NO",
                    "TIPO": "CHOQUE",
                    "HIPOTESIS": "POR ESTABLECER",
                    "POSIBLE_OCURRENCIA ": "COLISION CON VEHICULO TIPO CAMIONETA"
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-01-02T00:00:00",
                    "MES ": "ENERO",
                    "DIA": "LUNES",
                    "HORA": "11:20:00",
                    "RANGO_HORA": "09:00 a 11:59",
                    "SECCIONAL": "MEVIL",
                    "COORDENADAS": "4.132630, -73.607989",
                    "ADSCRITO": "DEMET",
                    "IDENTIFICACION": 1006794312,
                    "GRADO": "PT",
                    "NOMBRES": "JUAN FELIPE",
                    "APELLIDOS": "TORRES RAMIREZ",
                    "EDAD": 22,
                    "RANGO DE EDAD ": "18-22",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "SOLTERO",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "SI",
                    "PLACA": "LVJ76G",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2023,
                    "CC": 159,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "SI",
                    "RTM": "SI",
                    "LICENCIA": "SI",
                    "TIPO": "CHOQUE CON OBJETO FIJO",
                    "HIPOTESIS": "POR ESTABLECER",
                    "POSIBLE_OCURRENCIA ": "PIERDE EL CONTROL DE SU MOTOCICLETA Y COLISIONA CONTRA EL PAVIMENTO"
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-01-05T00:00:00",
                    "MES ": "ENERO",
                    "DIA": "JUEVES",
                    "HORA": "11:30:00",
                    "RANGO_HORA": "09:00 a 11:59",
                    "SECCIONAL": "DENOR",
                    "COORDENADAS": "8.139577, -72.715860",
                    "ADSCRITO": "DECES",
                    "IDENTIFICACION": 1090456211,
                    "GRADO": "SI",
                    "NOMBRES": "FREDDY ENRIQUE",
                    "APELLIDOS": "ROLON VEGA",
                    "EDAD": 30,
                    "RANGO DE EDAD ": "28-32",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "SOLTERO",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "NO",
                    "PLACA": "MIP045",
                    "CLASE_V": "AUTOMOVIL",
                    "MODELO": 2013,
                    "CC": 1500,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "SI",
                    "RTM": "SI",
                    "LICENCIA": "SI",
                    "TIPO": "CHOQUE CON OBJETO FIJO",
                    "HIPOTESIS": "HUECOS",
                    "POSIBLE_OCURRENCIA ": "HIPOTESIS POR ESQUIVAR UN HUECO Y EN EXCESO DE VELOCIDAD PERDIO EL CONTROL DE VEHICULO Y COLISIONA UN OBJETO FIJO (ARBOL) "
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-07-03T00:00:00",
                    "MES ": "JULIO",
                    "DIA": "LUNES",
                    "HORA": "13:50:00",
                    "RANGO_HORA": "12:00 a 14:59",
                    "SECCIONAL": "DECOR",
                    "COORDENADAS": "8.049746, -75.343312",
                    "ADSCRITO": "DECOR",
                    "IDENTIFICACION": 1143167068,
                    "GRADO": "PT",
                    "NOMBRES": "REINALDO JUNIOR ",
                    "APELLIDOS": "FIGUEROA ALMARALES",
                    "EDAD": 24,
                    "RANGO DE EDAD ": "23-27",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "SOLTERO",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "NO",
                    "PLACA": "EGD-47G",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2023,
                    "CC": 125,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "SI",
                    "RTM": "N/A",
                    "LICENCIA": "SI",
                    "TIPO": "CHOQUE",
                    "HIPOTESIS": "INVACION DE CARRIL ",
                    "POSIBLE_OCURRENCIA ": "VEHICULO TIPO CAMIONETA DE PLACAS TAQ903, REALIZA MANIOBRA PELIGROSA INVADE EL CARRIL CONTRARIO POR DONDE TRANSITA LA MOTOCICLETA, HACIENDO PERDER EL CONTROL DE LA MISMA Y COLICIONANDO CON LA CERCA, PERDIENDO LA VIDA DE FORMA INMEDIATA Y SU ACOMPANANTE QUEDA LESIONADA Y CON PRONOSTICO RESERVADO "
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-02-28T00:00:00",
                    "MES ": "FEBRERO",
                    "DIA": "MARTES",
                    "HORA": "14:30:00",
                    "RANGO_HORA": "12:00 a 14:59",
                    "SECCIONAL": "METIB",
                    "COORDENADAS": "4.443189, -75.210194",
                    "ADSCRITO": "METIB",
                    "IDENTIFICACION": 1005839493,
                    "GRADO": "PT",
                    "NOMBRES": "JAIDER DUVAN",
                    "APELLIDOS": "ESCOBAR GUTIERREZ",
                    "EDAD": 19,
                    "RANGO DE EDAD ": "18-22",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "SIN INFORMACION",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "SI",
                    "PLACA": "HYJ80G",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2013,
                    "CC": 150,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "SI",
                    "RTM": "N/A",
                    "LICENCIA": "NO",
                    "TIPO": "CHOQUE",
                    "HIPOTESIS": "DESOBEDECER SENALES DE TRANSITO.",
                    "POSIBLE_OCURRENCIA ": "CODIFICACION COMPARTIDA"
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-10-18T00:00:00",
                    "MES ": "OCTUBRE",
                    "DIA": "MIERCOLES",
                    "HORA": "14:30:00",
                    "RANGO_HORA": "12:00 a 14:59",
                    "SECCIONAL": "DECUN",
                    "COORDENADAS": "4.571688074213340, -74.16839561814370",
                    "ADSCRITO": "DETOL",
                    "IDENTIFICACION": 1070605511,
                    "GRADO": "PT",
                    "NOMBRES": "JONATHAN",
                    "APELLIDOS": "QUINTERO ARIAS ",
                    "EDAD": 32,
                    "RANGO DE EDAD ": "28-32",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "SOLTERO",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "POR ESTABLECER",
                    "PLACA": "OIQ80G",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2024,
                    "CC": 190,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "SI",
                    "RTM": "SI",
                    "LICENCIA": "N/A",
                    "TIPO": "VOLCAMIENTO LATERAL",
                    "HIPOTESIS": "INVACION DE CARRIL ",
                    "POSIBLE_OCURRENCIA ": "SUENO POR CANSANCIO "
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-07-14T00:00:00",
                    "MES ": "JULIO",
                    "DIA": "VIERNES",
                    "HORA": "15:30:00",
                    "RANGO_HORA": "15:00 a 17:59",
                    "SECCIONAL": "DEVAL",
                    "COORDENADAS": "4.62658, -75.933873",
                    "ADSCRITO": "DIJIN",
                    "IDENTIFICACION": 1113787624,
                    "GRADO": "PT",
                    "NOMBRES": "OSCAR FABIO ",
                    "APELLIDOS": "ESPINOSA VEGA",
                    "EDAD": 30,
                    "RANGO DE EDAD ": "28-32",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "SOLTERO",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "SI",
                    "PLACA": "DOB67G",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2023,
                    "CC": 149,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "SI",
                    "RTM": "N/A",
                    "LICENCIA": "SI",
                    "TIPO": "CHOQUE CON OBJETO FIJO",
                    "HIPOTESIS": "CHOQUE CON OBJETO FIJO (ARBOL)",
                    "POSIBLE_OCURRENCIA ": "CHOQUE CON OBJETO FIJO (ARBOL)"
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-05-18T00:00:00",
                    "MES ": "MAYO",
                    "DIA": "JUEVES",
                    "HORA": "15:40:00",
                    "RANGO_HORA": "15:00 a 17:59",
                    "SECCIONAL": "DENOR",
                    "COORDENADAS": "8.076728, -72.839140",
                    "ADSCRITO": "DEBOL",
                    "IDENTIFICACION": 1090380651,
                    "GRADO": "IT",
                    "NOMBRES": "JORGE ANDRES",
                    "APELLIDOS": "MEJIA PARADA",
                    "EDAD": 35,
                    "RANGO DE EDAD ": "33-37",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "CASADO",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "NO",
                    "PLACA": "YJK-31C",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2013,
                    "CC": 153,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "SI",
                    "RTM": "SI",
                    "LICENCIA": "SI",
                    "TIPO": "CHOQUE",
                    "HIPOTESIS": "INVASION CARRIL SENTIDO CONTRARIO",
                    "POSIBLE_OCURRENCIA ": "VEHICULO TRACTOCAMION INVADE EL CARRIL DEL SENTIDO CONTRARIO Y COLISIONA CON LA MOTOCICLETA"
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-01-16T00:00:00",
                    "MES ": "ENERO",
                    "DIA": "LUNES",
                    "HORA": "15:55:00",
                    "RANGO_HORA": "15:00 a 17:59",
                    "SECCIONAL": "MECAL",
                    "COORDENADAS": "3.333865, -76.293583",
                    "ADSCRITO": "MECAL",
                    "IDENTIFICACION": 1118297449,
                    "GRADO": "PT",
                    "NOMBRES": "FABIAN",
                    "APELLIDOS": "CABRERA LOPEZ",
                    "EDAD": 31,
                    "RANGO DE EDAD ": "28-32",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "SIN INFORMACION",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "NO",
                    "PLACA": "DEI19D",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2013,
                    "CC": 97,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "NO",
                    "RTM": "NO",
                    "LICENCIA": "SI",
                    "TIPO": "CHOQUE",
                    "HIPOTESIS": "OTRA.",
                    "POSIBLE_OCURRENCIA ": "POR ESTABLECER"
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-05-17T00:00:00",
                    "MES ": "MAYO",
                    "DIA": "MIERCOLES",
                    "HORA": "17:05:00",
                    "RANGO_HORA": "15:00 a 17:59",
                    "SECCIONAL": "DECUN",
                    "COORDENADAS": "4.197230, -73.767594",
                    "ADSCRITO": "DECUN",
                    "IDENTIFICACION": 1121819612,
                    "GRADO": "PT",
                    "NOMBRES": "ARLES ANTONIO",
                    "APELLIDOS": "NIETO FAJARDO",
                    "EDAD": 37,
                    "RANGO DE EDAD ": "33-37",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "UNION LIBRE",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "SI",
                    "PLACA": "FSC92C",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2020,
                    "CC": 250,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "SI",
                    "RTM": "SI",
                    "LICENCIA": "SI",
                    "TIPO": "CHOQUE",
                    "HIPOTESIS": "TRANSITAR EN CONTRAVIA",
                    "POSIBLE_OCURRENCIA ": "VEHICULO TIPO MOTOCICLETA TRANSITA EN SENTIDO CONTRARIO DE LA VIA"
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-01-17T00:00:00",
                    "MES ": "ENERO",
                    "DIA": "MARTES",
                    "HORA": "19:20:00",
                    "RANGO_HORA": "18:00 a 20:59",
                    "SECCIONAL": "DECAU",
                    "COORDENADAS": "2.251916, -77.243014",
                    "ADSCRITO": "DECAU",
                    "IDENTIFICACION": 1060104198,
                    "GRADO": "PT",
                    "NOMBRES": "ARVID ALIRIO",
                    "APELLIDOS": "VIVAS SANTACRUZ",
                    "EDAD": 31,
                    "RANGO DE EDAD ": "28-32",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "SIN INFORMACION",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "POR ESTABLECER",
                    "PLACA": "KHM81F",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2021,
                    "CC": 113,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "NO",
                    "RTM": "NO",
                    "LICENCIA": "SI",
                    "TIPO": "CHOQUE",
                    "HIPOTESIS": "POR ESTABLECER",
                    "POSIBLE_OCURRENCIA ": "ACCIDENTE DE TRANSITO POR CHOQUE, DECESO HOSPITALARIO"
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-02-05T00:00:00",
                    "MES ": "FEBRERO",
                    "DIA": "DOMINGO",
                    "HORA": "19:40:00",
                    "RANGO_HORA": "18:00 a 20:59",
                    "SECCIONAL": "DEATA",
                    "COORDENADAS": "10.585061, -75.193692",
                    "ADSCRITO": "MECAR",
                    "IDENTIFICACION": 1045229749,
                    "GRADO": "PT",
                    "NOMBRES": "RUBEN DARIO",
                    "APELLIDOS": "GUETTE REYES",
                    "EDAD": 34,
                    "RANGO DE EDAD ": "33-37",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "CASADO",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "SI",
                    "PLACA": "AAV09G",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2023,
                    "CC": 150,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "SI",
                    "RTM": "N/A",
                    "LICENCIA": "SI",
                    "TIPO": "VOLCAMIENTO LATERAL",
                    "HIPOTESIS": "PERDIDA DEL CONTROL DEL VEHICULO",
                    "POSIBLE_OCURRENCIA ": "PIERDE EL CONTROL DE LA MOTOCICLETA "
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-04-04T00:00:00",
                    "MES ": "ABRIL",
                    "DIA": "MARTES",
                    "HORA": "19:40:00",
                    "RANGO_HORA": "18:00 a 20:59",
                    "SECCIONAL": "DESUC",
                    "COORDENADAS": "9.413193, -75.097607",
                    "ADSCRITO": "DESUC",
                    "IDENTIFICACION": 1007712431,
                    "GRADO": "PT",
                    "NOMBRES": "DANILO",
                    "APELLIDOS": "RAMOS MARTINEZ",
                    "EDAD": 23,
                    "RANGO DE EDAD ": "23-27",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "SIN INFORMACION",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "POR ESTABLECER",
                    "PLACA": "LXT85G",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2023,
                    "CC": 200,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "SI",
                    "RTM": "N/A",
                    "LICENCIA": "SI",
                    "TIPO": "CHOQUE",
                    "HIPOTESIS": "POR ESTABLECER",
                    "POSIBLE_OCURRENCIA ": "IMPACTA CON UN VEHICULO DE FRENTE "
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-10-10T00:00:00",
                    "MES ": "OCTUBRE",
                    "DIA": "MARTES",
                    "HORA": "19:50:00",
                    "RANGO_HORA": "18:00 a 20:59",
                    "SECCIONAL": "MEBAR",
                    "COORDENADAS": "1.086817,-77.595260",
                    "ADSCRITO": "MESAN",
                    "IDENTIFICACION": 72284498,
                    "GRADO": "PT",
                    "NOMBRES": "ALBERT FRANCISCO ",
                    "APELLIDOS": "GUEVARA VASQUEZ",
                    "EDAD": 39,
                    "RANGO DE EDAD ": "38-42",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "UNION LIBRE",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "NO",
                    "PLACA": "JOZ25F",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2020,
                    "CC": 160,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "SI",
                    "RTM": "SI",
                    "LICENCIA": "SI",
                    "TIPO": "CHOQUE",
                    "HIPOTESIS": "REVERSA IMPRUDENTE",
                    "POSIBLE_OCURRENCIA ": "EL VEHICULO CAMA-BAJA SE DA LA HUIDA Y POSTERIORMENTE SE UBICA MAS ADELANTE"
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-05-03T00:00:00",
                    "MES ": "MAYO",
                    "DIA": "MIERCOLES",
                    "HORA": "21:20:00",
                    "RANGO_HORA": "21:00 a 23:59",
                    "SECCIONAL": "DETOL",
                    "COORDENADAS": "4.475451, -75.019027",
                    "ADSCRITO": "METIB",
                    "IDENTIFICACION": 2231444,
                    "GRADO": "IT",
                    "NOMBRES": "JUAN GABRIEL  ",
                    "APELLIDOS": "BOHORQUEZ VANEGAS",
                    "EDAD": 41,
                    "RANGO DE EDAD ": "38-42",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "CASADO",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "SI",
                    "PLACA": "CJV30C",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2023,
                    "CC": 124,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "SI",
                    "RTM": "N/A",
                    "LICENCIA": "SI",
                    "TIPO": "CHOQUE",
                    "HIPOTESIS": "104 ADELANTAR INVADIENDO CARRIL DEL SENTIDO CONTRARIO",
                    "POSIBLE_OCURRENCIA ": "104 ADELANTAR INVADIENDO CARRIL DEL SENTIDO CONTRARIO"
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-03-26T00:00:00",
                    "MES ": "MARZO",
                    "DIA": "DOMINGO",
                    "HORA": "21:30:00",
                    "RANGO_HORA": "21:00 a 23:59",
                    "SECCIONAL": "DESUC",
                    "COORDENADAS": "9.446586, -75.229777",
                    "ADSCRITO": "MEVAL",
                    "IDENTIFICACION": 1090421913,
                    "GRADO": "PT",
                    "NOMBRES": "WILLIAM HERNEY",
                    "APELLIDOS": "PENARANDA MENDOZA ",
                    "EDAD": 32,
                    "RANGO DE EDAD ": "28-32",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "CASADO",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "SI",
                    "PLACA": "NGN34D",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2015,
                    "CC": 153,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "SI",
                    "RTM": "NO",
                    "LICENCIA": "SI",
                    "TIPO": "VOLCAMIENTO LATERAL",
                    "HIPOTESIS": "SALIRSE DE LA CALZADA",
                    "POSIBLE_OCURRENCIA ": "SALIRSE DE LA CALZADA"
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-06-08T00:00:00",
                    "MES ": "JUNIO",
                    "DIA": "JUEVES",
                    "HORA": "23:09:00",
                    "RANGO_HORA": "21:00 a 23:59",
                    "SECCIONAL": "DEANT",
                    "COORDENADAS": " 6165587, -75.545110",
                    "ADSCRITO": "DEANT",
                    "IDENTIFICACION": 1054986335,
                    "GRADO": "PT",
                    "NOMBRES": "MARCIO ANDRES ",
                    "APELLIDOS": "VALENCIA MESSA ",
                    "EDAD": 37,
                    "RANGO DE EDAD ": "33-37",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "SIN INFORMACION",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "NO",
                    "PLACA": "N/A",
                    "CLASE_V": "N/A",
                    "MODELO": null,
                    "CC": "N/A",
                    "CLASE_S": "N/A",
                    "SOAT": "N/A",
                    "RTM": "N/A",
                    "LICENCIA": "N/A",
                    "TIPO": "N/A",
                    "HIPOTESIS": "PERDIDA DEL CONTROL DEL VEHICULO",
                    "POSIBLE_OCURRENCIA ": "SE ENCONTRABAN REALIZANDO LABORES DE REGISTRO Y CONTROL DE ANTECEDENTES 100 METROS ANTES DEL RESTAURANTE DE RAZON SOCIAL EL ZARZAR, PRACTICANDOLE UN REGISTRO PERSONAL A LOS PARTICULARES, FUERON ENVESTIDOS POR EL VEHICULO MARCA MINI COOPER, PLACA GBM-247, CONDUCIDO POR EL SENOR JOSE MANUEL CASTANO GALLEGO, QUIEN AL PARECER PIERDE EL CONTROL DEL VEHICULO POR EL PISO HUMEDO"
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-06-08T00:00:00",
                    "MES ": "JUNIO",
                    "DIA": "JUEVES",
                    "HORA": "23:09:00",
                    "RANGO_HORA": "21:00 a 23:59",
                    "SECCIONAL": "DEANT",
                    "COORDENADAS": " 6.165587, -75.545110",
                    "ADSCRITO": "DEANT",
                    "IDENTIFICACION": 1035910012,
                    "GRADO": "SI",
                    "NOMBRES": "FRANCISCO ADRIAN ",
                    "APELLIDOS": "LOPERA GALLEGO",
                    "EDAD": 37,
                    "RANGO DE EDAD ": "18-22",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "CASADO",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "NO",
                    "PLACA": "N/A",
                    "CLASE_V": "N/A",
                    "MODELO": null,
                    "CC": "N/A",
                    "CLASE_S": "N/A",
                    "SOAT": "N/A",
                    "RTM": "N/A",
                    "LICENCIA": "N/A",
                    "TIPO": "N/A",
                    "HIPOTESIS": "PERDIDA DEL CONTROL DEL VEHICULO",
                    "POSIBLE_OCURRENCIA ": "SE ENCONTRABAN REALIZANDO LABORES DE REGISTRO Y CONTROL DE ANTECEDENTES 100 METROS ANTES DEL RESTAURANTE DE RAZON SOCIAL EL ZARZAR, PRACTICANDOLE UN REGISTRO PERSONAL A LOS PARTICULARES, FUERON ENVESTIDOS POR EL VEHICULO MARCA MINI COOPER, PLACA GBM-247, CONDUCIDO POR EL SENOR JOSE MANUEL CASTANO GALLEGO, QUIEN AL PARECER PIERDE EL CONTROL DEL VEHICULO POR EL PISO HUMEDO"
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-01-09T00:00:00",
                    "MES ": "ENERO",
                    "DIA": "LUNES",
                    "HORA": "23:37:00",
                    "RANGO_HORA": "21:00 a 23:59",
                    "SECCIONAL": "DENAR",
                    "COORDENADAS": "1.32455, -77.19967",
                    "ADSCRITO": "MECAL",
                    "IDENTIFICACION": 1081595328,
                    "GRADO": "PT",
                    "NOMBRES": "JAIME FERNANDO",
                    "APELLIDOS": "MUTIZ MENESES",
                    "EDAD": 22,
                    "RANGO DE EDAD ": "18-22",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "SIN INFORMACION",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "SI",
                    "PLACA": "KRQ25F",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2021,
                    "CC": 162,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "NO",
                    "RTM": "N/A",
                    "LICENCIA": "SI",
                    "TIPO": "CHOQUE",
                    "HIPOTESIS": "DESOBEDECER SENALES DE TRANSITO.",
                    "POSIBLE_OCURRENCIA ": "CHOQUE CON OTRO VEHICULO"
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-02-15T00:00:00",
                    "MES ": "FEBRERO",
                    "DIA": "MIERCOLES",
                    "HORA": "23:40:00",
                    "RANGO_HORA": "21:00 a 23:59",
                    "SECCIONAL": "DEMAM",
                    "COORDENADAS": "70.55684, -73.850158",
                    "ADSCRITO": "DEMAM",
                    "IDENTIFICACION": 7255457,
                    "GRADO": "SI",
                    "NOMBRES": "WILMAN ANDRES",
                    "APELLIDOS": "MORENO CULMA",
                    "EDAD": 37,
                    "RANGO DE EDAD ": "33-37",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "SIN INFORMACION",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "NO",
                    "PLACA": "BOL05A",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2005,
                    "CC": 180,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "NO",
                    "RTM": "NO",
                    "LICENCIA": "SI",
                    "TIPO": "CHOQUE CON OBJETO FIJO",
                    "HIPOTESIS": "POR ESTABLECER",
                    "POSIBLE_OCURRENCIA ": "CHOQUE"
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-07-05T00:00:00",
                    "MES ": "JULIO",
                    "DIA": "MIERCOLES",
                    "HORA": "23:47:00",
                    "RANGO_HORA": "21:00 a 23:59",
                    "SECCIONAL": "MEPER",
                    "COORDENADAS": "4.810312, -75.700200",
                    "ADSCRITO": "MEPER",
                    "IDENTIFICACION": 1112778194,
                    "GRADO": "PT",
                    "NOMBRES": "OSCAR STIVEN",
                    "APELLIDOS": "MUNOZ VASQUEZ",
                    "EDAD": 30,
                    "RANGO DE EDAD ": "28-32",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "SOLTERO",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "SI",
                    "PLACA": "ZQB06E",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2020,
                    "CC": 98,
                    "CLASE_S": "PARTICULAR",
                    "SOAT": "SI",
                    "RTM": "SI",
                    "LICENCIA": "SI",
                    "TIPO": "CHOQUE",
                    "HIPOTESIS": null,
                    "POSIBLE_OCURRENCIA ": "TRANSITA EN CONTRAVIA"
                },
                {
                    "ANIO ": 2023,
                    "FECHA_OCURRENCIA": "2023-03-31T00:00:00",
                    "MES ": "MARZO",
                    "DIA": "VIERNES",
                    "HORA": "23:57:00",
                    "RANGO_HORA": "21:00 a 23:59",
                    "SECCIONAL": "MEBOG",
                    "COORDENADAS": "4.650745, -74.078299",
                    "ADSCRITO": "MEBOG",
                    "IDENTIFICACION": 80014061,
                    "GRADO": "IJ",
                    "NOMBRES": "LUIS ALBERTO",
                    "APELLIDOS": "CAMARGO HILARION",
                    "EDAD": 42,
                    "RANGO DE EDAD ": "38-42",
                    "GENERO": "MASCULINO",
                    "ESTADO CIVIL": "SIN INFORMACION",
                    "EMBRIAGUEZ": "POR ESTABLECER",
                    "RESPONSABILIDAD": "POR ESTABLECER",
                    "PLACA": "LNF68F",
                    "CLASE_V": "MOTOCICLETA",
                    "MODELO": 2021,
                    "CC": "OFICIAL",
                    "CLASE_S": "OFICIAL",
                    "SOAT": "SI",
                    "RTM": "SI",
                    "LICENCIA": "SI",
                    "TIPO": "CHOQUE",
                    "HIPOTESIS": "POR ESTABLECER",
                    "POSIBLE_OCURRENCIA ": "MATERIA DE INVESTIGACION "
                }
            ]
        }';

        $dataArray = json_decode($data, true);

        foreach ($dataArray['array'] as $dataItem) {
            DB::connection('ditra')->table('data_ditra')->insert([
                'year' => $dataItem['ANIO '],
                'occurrence_date' => $dataItem['FECHA_OCURRENCIA'],
                'month' => $dataItem['MES '],
                'day' => $dataItem['DIA'],
                'hour' => $dataItem['HORA'],
                'hour_range' => $dataItem['RANGO_HORA'],
                'sectional' => $dataItem['SECCIONAL'],
                'coordinates' => $dataItem['COORDENADAS'],
                'assigned' => $dataItem['ADSCRITO'],
                'identification' => $dataItem['IDENTIFICACION'],
                'grade' => $dataItem['GRADO'],
                'names' => $dataItem['NOMBRES'],
                'last_names' => $dataItem['APELLIDOS'],
                'age' => $dataItem['EDAD'],
                'age_range' => $dataItem['RANGO DE EDAD '],
                'gender' => $dataItem['GENERO'],
                'marital_status' => $dataItem['ESTADO CIVIL'],
                'intoxication' => $dataItem['EMBRIAGUEZ'],
                'responsibility' => $dataItem['RESPONSABILIDAD'],
                'plate' => $dataItem['PLACA'],
                'vehicle_class' => $dataItem['CLASE_V'],
                'model' => $dataItem['MODELO'],
                'cc' => $dataItem['CC'],
                'service_class' => $dataItem['CLASE_S'],
                'insurance' => $dataItem['SOAT'],
                'inspection' => $dataItem['RTM'],
                'license' => $dataItem['LICENCIA'],
                'type' => $dataItem['TIPO'],
                'hypothesis' => $dataItem['HIPOTESIS'],
                'possible_occurrence' => $dataItem['POSIBLE_OCURRENCIA '],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}