<?php

namespace Database\Seeders\Ditra;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
class TollboothTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = '{
            "array": [
                {
                    "IdPea": 3,
                    "Nombre": "CHINAUTA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP - Ampliacion a tercer carril doble calzada Bogota - Girardot",
                    "Electronic": 1,
                    "CodVia": 4005,
                    "Pr": null,
                    "Departamento": "Cundinamarca",
                    "Municipio": "Fusagasuga",
                    "Longitud": -74.5,
                    "Latitud": 4.269
                },
                {
                    "IdPea": 8,
                    "Nombre": "CHUSACA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP - Ampliacion a tercer carril doble calzada Bogota - Girardot",
                    "Electronic": 1,
                    "CodVia": 4005,
                    "Pr": null,
                    "Departamento": "Cundinamarca",
                    "Municipio": "Sibate",
                    "Longitud": -74.272,
                    "Latitud": 4.537
                },
                {
                    "IdPea": 26,
                    "Nombre": "CISNEROS",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP - Vias del Nus",
                    "Electronic": 1,
                    "CodVia": 4001,
                    "Pr": "PR 1 + 0.000",
                    "Departamento": "Antioquia",
                    "Municipio": "Cisneros",
                    "Longitud": -75.075,
                    "Latitud": 6.536
                },
                {
                    "IdPea": 176,
                    "Nombre": "PANDEQUESO",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP - Vias del Nus",
                    "Electronic": 1,
                    "CodVia": 2510,
                    "Pr": "KM 38 + 700.000",
                    "Departamento": "Antioquia",
                    "Municipio": "Don Matias",
                    "Longitud": -75.379,
                    "Latitud": 6.478
                },
                {
                    "IdPea": 178,
                    "Nombre": "TRAPICHE",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP - Vias del Nus",
                    "Electronic": 1,
                    "CodVia": 2510,
                    "Pr": "PR 14 + 900.000",
                    "Departamento": "Antioquia",
                    "Municipio": "Girardota",
                    "Longitud": -75.433,
                    "Latitud": 6.4
                },
                {
                    "IdPea": 173,
                    "Nombre": "CABILDO",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP - Vias del Nus",
                    "Electronic": 1,
                    "CodVia": 2510,
                    "Pr": "PR 14 + 900.000",
                    "Departamento": "Antioquia",
                    "Municipio": "Girardota",
                    "Longitud": -75.424,
                    "Latitud": 6.396
                },
                {
                    "IdPea": 57,
                    "Nombre": "PUENTE AMARILLO",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Villavicencio - Yopal",
                    "Electronic": 1,
                    "CodVia": 6510,
                    "Pr": null,
                    "Departamento": "Meta",
                    "Municipio": "Villavicencio",
                    "Longitud": -73.597,
                    "Latitud": 4.194
                },
                {
                    "IdPea": 22,
                    "Nombre": "VERACRUZ",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Villavicencio - Yopal",
                    "Electronic": 1,
                    "CodVia": 6510,
                    "Pr": null,
                    "Departamento": "Meta",
                    "Municipio": "Cumaral",
                    "Longitud": -73.448,
                    "Latitud": 4.261
                },
                {
                    "IdPea": 82,
                    "Nombre": "SAN PEDRO",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Villavicencio - Yopal",
                    "Electronic": 1,
                    "CodVia": 6511,
                    "Pr": "PR 15 + 0.000",
                    "Departamento": "Casanare",
                    "Municipio": "Villanueva",
                    "Longitud": -72.944,
                    "Latitud": 4.679
                },
                {
                    "IdPea": 2,
                    "Nombre": "CHICORAL",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP Girardot - Cajamarca.",
                    "Electronic": 1,
                    "CodVia": "4004B",
                    "Pr": "PR 17 + 300.000",
                    "Departamento": "Tolima",
                    "Municipio": "Flandes",
                    "Longitud": -74.881,
                    "Latitud": 4.246
                },
                {
                    "IdPea": 60,
                    "Nombre": "GUALANDAY",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP Girardot - Cajamarca.",
                    "Electronic": 1,
                    "CodVia": 4004,
                    "Pr": "PR 9 + 700.000",
                    "Departamento": "Tolima",
                    "Municipio": "Ibague",
                    "Longitud": -75.05,
                    "Latitud": 4.3
                },
                {
                    "IdPea": 110,
                    "Nombre": "COCORA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP Girardot - Cajamarca.",
                    "Electronic": 1,
                    "CodVia": null,
                    "Pr": "KM 13 + 790.821",
                    "Departamento": "Tolima",
                    "Municipio": "Ibague",
                    "Longitud": -75.286,
                    "Latitud": 4.406
                },
                {
                    "IdPea": 33,
                    "Nombre": "PAVAS",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Desarrollo Vial Armenia - Pereira - Manizales.",
                    "Electronic": 0,
                    "CodVia": "29CL03-1",
                    "Pr": "PR 1 + 200.000",
                    "Departamento": "Caldas",
                    "Municipio": "Manizales",
                    "Longitud": -75.587,
                    "Latitud": 5.027
                },
                {
                    "IdPea": 34,
                    "Nombre": "SANTAGUEDA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Desarrollo Vial Armenia - Pereira - Manizales.",
                    "Electronic": 0,
                    "CodVia": "29CL03",
                    "Pr": "PR 7 + 200.000",
                    "Departamento": "Caldas",
                    "Municipio": "Manizales",
                    "Longitud": -75.599,
                    "Latitud": 5.049
                },
                {
                    "IdPea": 35,
                    "Nombre": "SAN BERNARDO",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Desarrollo Vial Armenia - Pereira - Manizales.",
                    "Electronic": 0,
                    "CodVia": 5005,
                    "Pr": "PR 9 + 170.000",
                    "Departamento": "Caldas",
                    "Municipio": "Manizales",
                    "Longitud": -75.595,
                    "Latitud": 5.052
                },
                {
                    "IdPea": 77,
                    "Nombre": "CIRCASIA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Desarrollo Vial Armenia - Pereira - Manizales.",
                    "Electronic": 0,
                    "CodVia": 2901,
                    "Pr": "PR 16 + 850.000",
                    "Departamento": "Quindio",
                    "Municipio": "Filandia",
                    "Longitud": -75.606,
                    "Latitud": 4.698
                },
                {
                    "IdPea": 80,
                    "Nombre": "TARAPACA I",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Desarrollo Vial Armenia - Pereira - Manizales.",
                    "Electronic": 0,
                    "CodVia": 2902,
                    "Pr": "PR 20 + 800.000",
                    "Departamento": "Caldas",
                    "Municipio": "Chinchina",
                    "Longitud": -75.616,
                    "Latitud": 4.94
                },
                {
                    "IdPea": 76,
                    "Nombre": "COROZAL",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Desarrollo Vial Armenia - Pereira - Manizales.",
                    "Electronic": 0,
                    "CodVia": 4002,
                    "Pr": "PR 22 + 650.000",
                    "Departamento": "Valle del Cauca",
                    "Municipio": "Sevilla",
                    "Longitud": -75.9,
                    "Latitud": 4.408
                },
                {
                    "IdPea": 81,
                    "Nombre": "TARAPACA II",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Desarrollo Vial Armenia - Pereira - Manizales.",
                    "Electronic": 0,
                    "CodVia": "29RSC",
                    "Pr": "PR 24 + 800.000",
                    "Departamento": "Risaralda",
                    "Municipio": "Santa Rosa de Cabal",
                    "Longitud": -75.619,
                    "Latitud": 4.95
                },
                {
                    "IdPea": 14,
                    "Nombre": "CAIQUERO",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Santafe de Bogota (Puente el Cortijo) - Siberia - La Punta - El Vino - La Vega - Villeta",
                    "Electronic": 1,
                    "CodVia": 5008,
                    "Pr": "KM 67 + 950.000",
                    "Departamento": "Cundinamarca",
                    "Municipio": "Nocaima",
                    "Longitud": -74.414,
                    "Latitud": 5.065
                },
                {
                    "IdPea": 15,
                    "Nombre": "SIBERIA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Santafe de Bogota (Puente el Cortijo) - Siberia - La Punta - El Vino - La Vega - Villeta",
                    "Electronic": 1,
                    "CodVia": 5008,
                    "Pr": "KM 9 + 50.000",
                    "Departamento": "Cundinamarca",
                    "Municipio": "Tenjo",
                    "Longitud": -74.185,
                    "Latitud": 4.78
                },
                {
                    "IdPea": 43,
                    "Nombre": "GUARNE",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Desarrollo Vial del Oriente de Medellin - DEVIMED",
                    "Electronic": 1,
                    "CodVia": 6004,
                    "Pr": "KM 7 + 100.000",
                    "Departamento": "Antioquia",
                    "Municipio": "Copacabana",
                    "Longitud": -75.516,
                    "Latitud": 6.328
                },
                {
                    "IdPea": 40,
                    "Nombre": "LAS PALMAS",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Desarrollo Vial del Oriente de Medellin - DEVIMED",
                    "Electronic": 1,
                    "CodVia": 5601,
                    "Pr": "KM 10 + 700.000",
                    "Departamento": "Antioquia",
                    "Municipio": "Retiro",
                    "Longitud": -75.531,
                    "Latitud": 6.151
                },
                {
                    "IdPea": 11,
                    "Nombre": "RIO BOGOTA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Bogota (Fontibon) - Faca - Los Alpes",
                    "Electronic": 1,
                    "CodVia": "5008A",
                    "Pr": "PR 71 + 500.000",
                    "Departamento": "Cundinamarca",
                    "Municipio": "Mosquera",
                    "Longitud": -74.179,
                    "Latitud": 4.699
                },
                {
                    "IdPea": 13,
                    "Nombre": "CORZO",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Bogota (Fontibon) - Faca - Los Alpes",
                    "Electronic": 1,
                    "CodVia": "5008A",
                    "Pr": "PR 55 + 500.000",
                    "Departamento": "Cundinamarca",
                    "Municipio": "Madrid",
                    "Longitud": -74.291,
                    "Latitud": 4.749
                },
                {
                    "IdPea": 108,
                    "Nombre": "NEGUANJE",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Santa Marta - Riohacha - Paraguachon",
                    "Electronic": 0,
                    "CodVia": 9008,
                    "Pr": "PR 6 + 700.000",
                    "Departamento": "Magdalena",
                    "Municipio": "Santa Marta",
                    "Longitud": -74.109,
                    "Latitud": 11.253
                },
                {
                    "IdPea": 62,
                    "Nombre": "EL EBANAL",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Santa Marta - Riohacha - Paraguachon",
                    "Electronic": 0,
                    "CodVia": 9009,
                    "Pr": "PR 53 + 950.000",
                    "Departamento": "La Guajira",
                    "Municipio": "Riohacha",
                    "Longitud": -73.122,
                    "Latitud": 11.276
                },
                {
                    "IdPea": 63,
                    "Nombre": "ALTO PINO",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Santa Marta - Riohacha - Paraguachon",
                    "Electronic": 0,
                    "CodVia": 9010,
                    "Pr": "PR 41 + 120.000",
                    "Departamento": "La Guajira",
                    "Municipio": "Manaure",
                    "Longitud": -72.543,
                    "Latitud": 11.445
                },
                {
                    "IdPea": 64,
                    "Nombre": "PARAGUACHON",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Santa Marta - Riohacha - Paraguachon",
                    "Electronic": 0,
                    "CodVia": 9010,
                    "Pr": "PR 84 + 450.000",
                    "Departamento": "La Guajira",
                    "Municipio": "Maicao",
                    "Longitud": -72.157,
                    "Latitud": 11.368
                },
                {
                    "IdPea": 23,
                    "Nombre": "EL ROBLE",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Briceno - Tunja - Sogamoso",
                    "Electronic": 0,
                    "CodVia": 5501,
                    "Pr": "PR 36 + 660.000",
                    "Departamento": "Cundinamarca",
                    "Municipio": "Sesquile",
                    "Longitud": -73.84,
                    "Latitud": 5.031
                },
                {
                    "IdPea": 25,
                    "Nombre": "ALBARRACIN",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Briceno - Tunja - Sogamoso",
                    "Electronic": 0,
                    "CodVia": 5501,
                    "Pr": "PR 82 + 252.000",
                    "Departamento": "Cundinamarca",
                    "Municipio": "Villapinzon",
                    "Longitud": -73.584,
                    "Latitud": 5.291
                },
                {
                    "IdPea": 83,
                    "Nombre": "TUTA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Briceno - Tunja - Sogamoso",
                    "Electronic": 0,
                    "CodVia": 5502,
                    "Pr": "PR 12 + 90.000",
                    "Departamento": "Boyaca",
                    "Municipio": "Combita",
                    "Longitud": -73.278,
                    "Latitud": 5.657
                },
                {
                    "IdPea": 47,
                    "Nombre": "LOS GARZONES 2",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Cordoba - Sucre",
                    "Electronic": 0,
                    "CodVia": 9004,
                    "Pr": "PR 6 + 130.000",
                    "Departamento": "Cordoba",
                    "Municipio": "Monteria",
                    "Longitud": -75.837,
                    "Latitud": 8.828
                },
                {
                    "IdPea": 24,
                    "Nombre": "MACHETA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Transversal del Sisga",
                    "Electronic": 1,
                    "CodVia": 5607,
                    "Pr": "PR 27 + 240.000",
                    "Departamento": "Cundinamarca",
                    "Municipio": "Macheta",
                    "Longitud": -73.553,
                    "Latitud": 5.077
                },
                {
                    "IdPea": 67,
                    "Nombre": "ALTAMIRA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Santana - Mocoa - Neiva",
                    "Electronic": 0,
                    "CodVia": 4504,
                    "Pr": "PR 60 + 507.000",
                    "Departamento": "Huila",
                    "Municipio": "Altamira",
                    "Longitud": -75.701,
                    "Latitud": 2.143
                },
                {
                    "IdPea": 51,
                    "Nombre": "LOS CAUCHOS",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Santana - Mocoa - Neiva",
                    "Electronic": 0,
                    "CodVia": 4505,
                    "Pr": "PR 98 + 500.000",
                    "Departamento": "Huila",
                    "Municipio": "Rivera",
                    "Longitud": -75.302,
                    "Latitud": 2.786
                },
                {
                    "IdPea": 96,
                    "Nombre": "CALAMAR",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Puerta de Hierro - Palmar de Varela y Carreto - Cruz del Viso",
                    "Electronic": 0,
                    "CodVia": 2515,
                    "Pr": "PR 131 + 76.000",
                    "Departamento": "Bolivar",
                    "Municipio": "Calamar",
                    "Longitud": -74.945,
                    "Latitud": 10.208
                },
                {
                    "IdPea": 91,
                    "Nombre": "EL CARMEN",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Puerta de Hierro - Palmar de Varela y Carreto - Cruz del Viso",
                    "Electronic": 0,
                    "CodVia": 2515,
                    "Pr": "PR 60 + 650.000",
                    "Departamento": "Bolivar",
                    "Municipio": "El Carmen de Bolivar",
                    "Longitud": -75.125,
                    "Latitud": 9.682
                },
                {
                    "IdPea": 136,
                    "Nombre": "SOPO",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Perimetral de Oriente de Cundinamarca",
                    "Electronic": 1,
                    "CodVia": "50CN03",
                    "Pr": "PR 2 + 200.000",
                    "Departamento": "Cundinamarca",
                    "Municipio": "Sopo",
                    "Longitud": -73.936,
                    "Latitud": 4.842
                },
                {
                    "IdPea": 18,
                    "Nombre": "LA CABANA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Perimetral de Oriente de Cundinamarca",
                    "Electronic": 1,
                    "CodVia": 5009,
                    "Pr": "PR 21 + 650.000",
                    "Departamento": "Cundinamarca",
                    "Municipio": "Guasca",
                    "Longitud": -73.946,
                    "Latitud": 4.809
                },
                {
                    "IdPea": 12,
                    "Nombre": "LOS PATIOS",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Perimetral de Oriente de Cundinamarca",
                    "Electronic": 1,
                    "CodVia": 5009,
                    "Pr": "PR 0 + 0.000",
                    "Departamento": "Bogota, D.C.",
                    "Municipio": "Bogota, D.C.",
                    "Longitud": -74.011,
                    "Latitud": 4.663
                },
                {
                    "IdPea": 30,
                    "Nombre": "EL PLACER",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Rumichaca - Pasto",
                    "Electronic": 1,
                    "CodVia": 2501,
                    "Pr": "PR 0 + 0.000",
                    "Departamento": "Narino",
                    "Municipio": "Tangua",
                    "Longitud": -77.428,
                    "Latitud": 1.065
                },
                {
                    "IdPea": 221,
                    "Nombre": "ETD 10+850",
                    "Estado": "Suspendido",
                    "Proyecto": "Rumichaca - Pasto",
                    "Electronic": 0,
                    "CodVia": null,
                    "Pr": "PR 10 + 850.000",
                    "Departamento": "Narino",
                    "Municipio": "Ipiales",
                    "Longitud": -77.586,
                    "Latitud": 0.847
                },
                {
                    "IdPea": 216,
                    "Nombre": "EL CONTADERO",
                    "Estado": "Suspendido",
                    "Proyecto": "Rumichaca - Pasto",
                    "Electronic": 1,
                    "CodVia": 3001,
                    "Pr": "PR 0 + 0.000",
                    "Departamento": "Narino",
                    "Municipio": "Contadero",
                    "Longitud": -77.513,
                    "Latitud": 0.934
                },
                {
                    "IdPea": 54,
                    "Nombre": "FLANDES",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP Neiva - Espinal - Girardot.",
                    "Electronic": 1,
                    "CodVia": 4507,
                    "Pr": "PR 155 + 270.000",
                    "Departamento": "Tolima",
                    "Municipio": "Espinal",
                    "Longitud": -74.861,
                    "Latitud": 4.192
                },
                {
                    "IdPea": 53,
                    "Nombre": "EL PATA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP Neiva - Espinal - Girardot.",
                    "Electronic": 1,
                    "CodVia": 4506,
                    "Pr": "PR 53 + 400.000",
                    "Departamento": "Huila",
                    "Municipio": "Aipe",
                    "Longitud": -75.204,
                    "Latitud": 3.394
                },
                {
                    "IdPea": 52,
                    "Nombre": "NEIVA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP Neiva - Espinal - Girardot.",
                    "Electronic": 0,
                    "CodVia": 4506,
                    "Pr": "PR 3 + 300.000",
                    "Departamento": "Huila",
                    "Municipio": "Neiva",
                    "Longitud": -75.307,
                    "Latitud": 2.978
                },
                {
                    "IdPea": 84,
                    "Nombre": "YUCAO",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP - Malla vial del Meta",
                    "Electronic": 0,
                    "CodVia": 4008,
                    "Pr": "PR 99 + 180.000",
                    "Departamento": "Meta",
                    "Municipio": "Puerto Lopez",
                    "Longitud": -72.169,
                    "Latitud": 4.351
                },
                {
                    "IdPea": 59,
                    "Nombre": "CASETABLA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP - Malla vial del Meta",
                    "Electronic": 0,
                    "CodVia": 4008,
                    "Pr": "PR 16 + 230.000",
                    "Departamento": "Meta",
                    "Municipio": "Puerto Lopez",
                    "Longitud": -72.835,
                    "Latitud": 4.113
                },
                {
                    "IdPea": 58,
                    "Nombre": "LA LIBERTAD",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP - Malla vial del Meta",
                    "Electronic": 0,
                    "CodVia": 4007,
                    "Pr": "PR 17 + 570.000",
                    "Departamento": "Meta",
                    "Municipio": "Villavicencio",
                    "Longitud": -73.463,
                    "Latitud": 4.057
                },
                {
                    "IdPea": 56,
                    "Nombre": "OCOA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP - Malla vial del Meta",
                    "Electronic": 0,
                    "CodVia": 6509,
                    "Pr": "PR 54 + 670.000",
                    "Departamento": "Meta",
                    "Municipio": "Acacias",
                    "Longitud": -73.775,
                    "Latitud": 4.026
                },
                {
                    "IdPea": 55,
                    "Nombre": "IRACA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP - Malla vial del Meta",
                    "Electronic": 0,
                    "CodVia": 6509,
                    "Pr": "PR 6 + 800.000",
                    "Departamento": "Meta",
                    "Municipio": "Granada",
                    "Longitud": -73.706,
                    "Latitud": 3.633
                },
                {
                    "IdPea": 21,
                    "Nombre": "PIPIRAL",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP - Chirajara - Fundadores",
                    "Electronic": 1,
                    "CodVia": 4006,
                    "Pr": "KM 71 + 850.000",
                    "Departamento": "Meta",
                    "Municipio": "Villavicencio",
                    "Longitud": -73.721,
                    "Latitud": 4.2
                },
                {
                    "IdPea": 20,
                    "Nombre": "NARANJAL",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP - Chirajara - Fundadores",
                    "Electronic": 1,
                    "CodVia": 4006,
                    "Pr": "KM 50 + 100.000",
                    "Departamento": "Cundinamarca",
                    "Municipio": "Quetame",
                    "Longitud": -73.835,
                    "Latitud": 4.28
                },
                {
                    "IdPea": 10,
                    "Nombre": "BOQUERON II",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP - Chirajara - Fundadores",
                    "Electronic": 1,
                    "CodVia": 4006,
                    "Pr": "KM 9 + 200.000",
                    "Departamento": "Cundinamarca",
                    "Municipio": "Chipaque",
                    "Longitud": -74.05,
                    "Latitud": 4.455
                },
                {
                    "IdPea": 9,
                    "Nombre": "BOQUERON I",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP - Chirajara - Fundadores",
                    "Electronic": 1,
                    "CodVia": 4006,
                    "Pr": "KM 4 + 100.000",
                    "Departamento": "Cundinamarca",
                    "Municipio": "Chipaque",
                    "Longitud": -74.073,
                    "Latitud": 4.453
                },
                {
                    "IdPea": 111,
                    "Nombre": "ARMERO",
                    "Estado": "Funcionamiento",
                    "Proyecto": "APP IP - Cambao - Manizales.",
                    "Electronic": 0,
                    "CodVia": null,
                    "Pr": "PR 55 + 850.000",
                    "Departamento": "Tolima",
                    "Municipio": "Lerida",
                    "Longitud": -74.914,
                    "Latitud": 4.958
                },
                {
                    "IdPea": 4,
                    "Nombre": "HONDA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "APP IP - Cambao - Manizales.",
                    "Electronic": 1,
                    "CodVia": 5007,
                    "Pr": "PR 35 + 100.000",
                    "Departamento": "Tolima",
                    "Municipio": "Honda",
                    "Longitud": -74.82,
                    "Latitud": 5.202
                },
                {
                    "IdPea": 1,
                    "Nombre": "ALVARADO",
                    "Estado": "Funcionamiento",
                    "Proyecto": "APP IP - Cambao - Manizales.",
                    "Electronic": 1,
                    "CodVia": 4305,
                    "Pr": "PR 19 + 855.000",
                    "Departamento": "Tolima",
                    "Municipio": "Alvarado",
                    "Longitud": -74.992,
                    "Latitud": 4.508
                },
                {
                    "IdPea": 126,
                    "Nombre": "BRISAS",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Honda - Puerto Salgar - Girardot",
                    "Electronic": 1,
                    "CodVia": 4501,
                    "Pr": "PR 10 + 200.000",
                    "Departamento": "Cundinamarca",
                    "Municipio": "Puerto Salgar",
                    "Longitud": -74.64,
                    "Latitud": 5.459
                },
                {
                    "IdPea": 124,
                    "Nombre": "CAMBAO",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Honda - Puerto Salgar - Girardot",
                    "Electronic": 1,
                    "CodVia": 4509,
                    "Pr": "PR 5 + 900.000",
                    "Departamento": "Cundinamarca",
                    "Municipio": "San Juan de Rio Seco",
                    "Longitud": -74.719,
                    "Latitud": 4.946
                },
                {
                    "IdPea": 135,
                    "Nombre": "GUATAQUI",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Honda - Puerto Salgar - Girardot",
                    "Electronic": 1,
                    "CodVia": 4508,
                    "Pr": "PR 46 + 500.000",
                    "Departamento": "Cundinamarca",
                    "Municipio": "Guataqui",
                    "Longitud": -74.797,
                    "Latitud": 4.564
                },
                {
                    "IdPea": 65,
                    "Nombre": "LOS ACACIOS",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Pamplona - Cucuta",
                    "Electronic": 1,
                    "CodVia": 5505,
                    "Pr": "PR 119 + 693.000",
                    "Departamento": "Norte de Santander",
                    "Municipio": "Los Patios",
                    "Longitud": -72.571,
                    "Latitud": 7.721
                },
                {
                    "IdPea": 144,
                    "Nombre": "PAMPLONITA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Pamplona - Cucuta",
                    "Electronic": 0,
                    "CodVia": 5505,
                    "Pr": "PR 78 + 210.000",
                    "Departamento": "Norte de Santander",
                    "Municipio": "Pamplonita",
                    "Longitud": -72.619,
                    "Latitud": 7.421
                },
                {
                    "IdPea": 85,
                    "Nombre": "EL PICACHO",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Bucaramanga - Pamplona",
                    "Electronic": 0,
                    "CodVia": 6603,
                    "Pr": "PR 48 + 0.000",
                    "Departamento": "Santander",
                    "Municipio": "Piedecuesta",
                    "Longitud": -72.969,
                    "Latitud": 7.108
                },
                {
                    "IdPea": 123,
                    "Nombre": "JUAN MINA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Cartagena - Barranquilla y Circunvalar de la Prosperidad",
                    "Electronic": 1,
                    "CodVia": "25AT04",
                    "Pr": "PR 20 + 300.000",
                    "Departamento": "Atlantico",
                    "Municipio": "Galapa",
                    "Longitud": -74.894,
                    "Latitud": 10.929
                },
                {
                    "IdPea": 103,
                    "Nombre": "GALAPA 02",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Cartagena - Barranquilla y Circunvalar de la Prosperidad",
                    "Electronic": 1,
                    "CodVia": "25AT04",
                    "Pr": "PR 12 + 700.000",
                    "Departamento": "Atlantico",
                    "Municipio": "Galapa",
                    "Longitud": -74.845,
                    "Latitud": 10.887
                },
                {
                    "IdPea": 106,
                    "Nombre": "PAPIROS",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Cartagena - Barranquilla y Circunvalar de la Prosperidad",
                    "Electronic": 1,
                    "CodVia": "90A01",
                    "Pr": "PR 103 + 800.000",
                    "Departamento": "Atlantico",
                    "Municipio": "Puerto Colombia",
                    "Longitud": -74.89,
                    "Latitud": 11.013
                },
                {
                    "IdPea": 104,
                    "Nombre": "PUERTO COLOMBIA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Cartagena - Barranquilla y Circunvalar de la Prosperidad",
                    "Electronic": 1,
                    "CodVia": "90A01",
                    "Pr": "PR 93 + 600.000",
                    "Departamento": "Atlantico",
                    "Municipio": "Tubara",
                    "Longitud": -74.956,
                    "Latitud": 10.968
                },
                {
                    "IdPea": 101,
                    "Nombre": "MARAHUACO",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Cartagena - Barranquilla y Circunvalar de la Prosperidad",
                    "Electronic": 1,
                    "CodVia": "90A01",
                    "Pr": "PR 15 + 110.000",
                    "Departamento": "Bolivar",
                    "Municipio": "Cartagena",
                    "Longitud": -75.451,
                    "Latitud": 10.575
                },
                {
                    "IdPea": 115,
                    "Nombre": "LA LIZAMA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Bucaramanga - Barrancabermeja - Yondo",
                    "Electronic": 1,
                    "CodVia": 6601,
                    "Pr": "PR 18 + 100.000",
                    "Departamento": "Santander",
                    "Municipio": "Barrancabermeja",
                    "Longitud": -73.717,
                    "Latitud": 7.084
                },
                {
                    "IdPea": 117,
                    "Nombre": "ZARAGOZA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "APP - Conexion Norte.",
                    "Electronic": 1,
                    "CodVia": "25AN17",
                    "Pr": "PR 21 + 310.000",
                    "Departamento": "Antioquia",
                    "Municipio": "Zaragoza",
                    "Longitud": -74.895,
                    "Latitud": 7.633
                },
                {
                    "IdPea": 27,
                    "Nombre": "PUERTO BERRIO",
                    "Estado": "Funcionamiento",
                    "Proyecto": "APP Autopista al Rio Magdalena 2.",
                    "Electronic": 1,
                    "CodVia": 6206,
                    "Pr": "PR 85 + 10.000",
                    "Departamento": "Antioquia",
                    "Municipio": "Puerto Berrio",
                    "Longitud": -74.501,
                    "Latitud": 6.497
                },
                {
                    "IdPea": 171,
                    "Nombre": "CIRILO",
                    "Estado": "Suspendido",
                    "Proyecto": "Autopista al Mar 2",
                    "Electronic": 0,
                    "CodVia": 9001,
                    "Pr": "PR 18 + 70.000",
                    "Departamento": "Antioquia",
                    "Municipio": "Turbo",
                    "Longitud": -76.745,
                    "Latitud": 8.213
                },
                {
                    "IdPea": 185,
                    "Nombre": "ABURRA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Autopista al Mar 1",
                    "Electronic": 1,
                    "CodVia": "6204A",
                    "Pr": "PR 45 + 300.000",
                    "Departamento": "Antioquia",
                    "Municipio": "Medellin",
                    "Longitud": -75.651,
                    "Latitud": 6.293
                },
                {
                    "IdPea": 128,
                    "Nombre": "IRRA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Autopista Conexion Pacifico 3",
                    "Electronic": 1,
                    "CodVia": 2903,
                    "Pr": "PR 36 + 750.000",
                    "Departamento": "Caldas",
                    "Municipio": "Neira",
                    "Longitud": -75.657,
                    "Latitud": 5.258
                },
                {
                    "IdPea": 79,
                    "Nombre": "ACAPULCO",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Autopista Conexion Pacifico 3",
                    "Electronic": 1,
                    "CodVia": 2507,
                    "Pr": "PR 24 + 20.000",
                    "Departamento": "Caldas",
                    "Municipio": "Belalcazar",
                    "Longitud": -75.859,
                    "Latitud": 4.999
                },
                {
                    "IdPea": 36,
                    "Nombre": "SUPIA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Autopista Conexion Pacifico 3",
                    "Electronic": 0,
                    "CodVia": 2508,
                    "Pr": "PR 81 + 510.000",
                    "Departamento": "Antioquia",
                    "Municipio": "Caramanta",
                    "Longitud": -75.57,
                    "Latitud": 5.541
                },
                {
                    "IdPea": 127,
                    "Nombre": "GUAICO",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Autopista Conexion Pacifico 3",
                    "Electronic": 1,
                    "CodVia": "5004B",
                    "Pr": "PR 9 + 235.000",
                    "Departamento": "Caldas",
                    "Municipio": "Risaralda",
                    "Longitud": -75.76,
                    "Latitud": 5.106
                },
                {
                    "IdPea": 37,
                    "Nombre": "LA PINTADA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Autopista Conexion Pacifico 2",
                    "Electronic": 1,
                    "CodVia": "25B01",
                    "Pr": "PR 12 + 710.000",
                    "Departamento": "Antioquia",
                    "Municipio": "Jerico",
                    "Longitud": -75.679,
                    "Latitud": 5.812
                },
                {
                    "IdPea": 38,
                    "Nombre": "PRIMAVERA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Autopista Conexion Pacifico 2",
                    "Electronic": 1,
                    "CodVia": 2509,
                    "Pr": "PR 38 + 800.000",
                    "Departamento": "Antioquia",
                    "Municipio": "Santa Barbara",
                    "Longitud": -75.594,
                    "Latitud": 5.969
                },
                {
                    "IdPea": 220,
                    "Nombre": "ANCON SUR",
                    "Estado": "Suspendido",
                    "Proyecto": "Autopista Conexion Pacifico 1",
                    "Electronic": 0,
                    "CodVia": 2509,
                    "Pr": "PR 54 + 700.000",
                    "Departamento": "Antioquia",
                    "Municipio": "Caldas",
                    "Longitud": -75.636,
                    "Latitud": 6.091
                },
                {
                    "IdPea": 39,
                    "Nombre": "AMAGA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "Autopista Conexion Pacifico 1",
                    "Electronic": 0,
                    "CodVia": 6003,
                    "Pr": "PR 89 + 396.000",
                    "Departamento": "Antioquia",
                    "Municipio": "Caldas",
                    "Longitud": -75.66,
                    "Latitud": 6.047
                },
                {
                    "IdPea": 90,
                    "Nombre": "SAN ONOFRE",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP - Antioquia - Bolivar",
                    "Electronic": 1,
                    "CodVia": 9005,
                    "Pr": "PR 21 + 500.000",
                    "Departamento": "Sucre",
                    "Municipio": "San Onofre",
                    "Longitud": -75.393,
                    "Latitud": 9.873
                },
                {
                    "IdPea": 50,
                    "Nombre": "CAIMANERA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP - Antioquia - Bolivar",
                    "Electronic": 1,
                    "CodVia": 9004,
                    "Pr": "PR 41 + 150.000",
                    "Departamento": "Sucre",
                    "Municipio": "Covenas",
                    "Longitud": -75.607,
                    "Latitud": 9.466
                },
                {
                    "IdPea": 49,
                    "Nombre": "MATA DE CANA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP - Antioquia - Bolivar",
                    "Electronic": 1,
                    "CodVia": 2103,
                    "Pr": "PR 32 + 500.000",
                    "Departamento": "Cordoba",
                    "Municipio": "Lorica",
                    "Longitud": -75.82,
                    "Latitud": 9.091
                },
                {
                    "IdPea": 139,
                    "Nombre": "SAN CARLOS",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP - Antioquia - Bolivar",
                    "Electronic": 1,
                    "CodVia": 4514,
                    "Pr": "KM 9 + 660.000",
                    "Departamento": "Cordoba",
                    "Municipio": "San Carlos",
                    "Longitud": -75.717,
                    "Latitud": 8.71
                },
                {
                    "IdPea": 46,
                    "Nombre": "CEDROS",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP - Antioquia - Bolivar",
                    "Electronic": 1,
                    "CodVia": 7401,
                    "Pr": "PR 47 + 0.000",
                    "Departamento": "Cordoba",
                    "Municipio": "Monteria",
                    "Longitud": -75.999,
                    "Latitud": 8.82
                },
                {
                    "IdPea": 45,
                    "Nombre": "PURGATORIO",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP - Antioquia - Bolivar",
                    "Electronic": 1,
                    "CodVia": 2310,
                    "Pr": "PR 32 + 600.000",
                    "Departamento": "Cordoba",
                    "Municipio": "Monteria",
                    "Longitud": -75.764,
                    "Latitud": 8.631
                },
                {
                    "IdPea": 44,
                    "Nombre": "MANGUITOS",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP - Antioquia - Bolivar",
                    "Electronic": 1,
                    "CodVia": 2513,
                    "Pr": "PR 52 + 200.000",
                    "Departamento": "Cordoba",
                    "Municipio": "Planeta Rica",
                    "Longitud": -75.53,
                    "Latitud": 8.302
                },
                {
                    "IdPea": 28,
                    "Nombre": "LA APARTADA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP - Antioquia - Bolivar",
                    "Electronic": 1,
                    "CodVia": 2513,
                    "Pr": "PR 11 + 800.000",
                    "Departamento": "Cordoba",
                    "Municipio": "La Apartada",
                    "Longitud": -75.303,
                    "Latitud": 8.032
                },
                {
                    "IdPea": 19,
                    "Nombre": "UNISABANA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP - Accesos Norte a Bogota",
                    "Electronic": 1,
                    "CodVia": "45A04",
                    "Pr": "PR 5 + 700.000",
                    "Departamento": "Cundinamarca",
                    "Municipio": "Chia",
                    "Longitud": -74.031,
                    "Latitud": 4.855
                },
                {
                    "IdPea": 16,
                    "Nombre": "ANDES",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP - Accesos Norte a Bogota",
                    "Electronic": 1,
                    "CodVia": "45A04",
                    "Pr": "PR 2 + 800.000",
                    "Departamento": "Cundinamarca",
                    "Municipio": "Chia",
                    "Longitud": -74.033,
                    "Latitud": 4.83
                },
                {
                    "IdPea": 17,
                    "Nombre": "FUSCA",
                    "Estado": "Funcionamiento",
                    "Proyecto": "IP - Accesos Norte a Bogota",
                    "Electronic": 1,
                    "CodVia": 5501,
                    "Pr": "PR 3 + 900.000",
                    "Departamento": "Cundinamarca",
                    "Municipio": "Chia",
                    "Longitud": -74.029,
                    "Latitud": 4.835
                },
                {
                    "IdPea": 215,
                    "Nombre": "ARROYO DE PIEDRA",
                    "Estado": "Suspendido",
                    "Proyecto": "IP Autopistas del Caribe, corredor de carga Cartagena - Barranquilla",
                    "Electronic": 0,
                    "CodVia": 9006,
                    "Pr": "PR 62 + 35.000",
                    "Departamento": "Atlantico",
                    "Municipio": "Repelon",
                    "Longitud": -75.067,
                    "Latitud": 10.65
                },
                {
                    "IdPea": 175,
                    "Nombre": "NIQUIA",
                    "Estado": "Suspendido",
                    "Proyecto": "IP - Vias del Nus",
                    "Electronic": 0,
                    "CodVia": null,
                    "Pr": "PR 2 + 200.000",
                    "Departamento": "Antioquia",
                    "Municipio": "Bello",
                    "Longitud": -75.527,
                    "Latitud": 6.345
                }
            ]
        }';
//        'uuid', 'id_peaje', 'name', 'state', 'project', 'electronic', 'cod_via', 'pr', 'department', 'municipality', 'coordinates'
        $dataArray = json_decode($data, true);

        foreach ($dataArray['array'] as $dataItem) {
            $uuid = Str::uuid();
            DB::table('tollbooth')->insert([
                'uuid' => $uuid,
                'id_peaje' => $dataItem['IdPea'],
                'name' => $dataItem['Nombre'],
                'state' => $dataItem['Estado'],
                'project' => $dataItem['Proyecto'],
                'electronic' => $dataItem['Electronic'],
                'cod_via' => $dataItem['CodVia'],
                'pr' => $dataItem['Pr'],
                'department' => $dataItem['Departamento'],
                'municipality' => $dataItem['Municipio'],
                'latitude' => $dataItem['Latitud'],
                'longitude' => $dataItem['Longitud'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
