version: "3.7"
services:
  app:
    build:
      args:
        user: ignicion
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: medusa
    container_name: medusa-app
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - 6001:6001
    volumes:
      - ./:/var/www
    networks:
      - medusa

  nginx:
    image: nginx:alpine
    container_name: medusa-nginx
    restart: unless-stopped
    ports:
      - 81:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - medusa

  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: ignicion
      POSTGRES_DB: medusa
    networks:
      - medusa

  pgadmin:
    image: dpage/pgadmin4
    container_name: "pgadmin_container"
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ignicion@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
      POSTGRES_PASSWORD: root
      POSTGRES_USER: ignicion
      POSTGRES_DB: medusa
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  medusa:
    driver: bridge
