<?php

namespace Database\Seeders\Villavicencio;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;


class NeighborhoodTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = '
        {
          "array":[
    {"barrio": "Nueva Granada", "comuna_id": 1},
    {"barrio": "Rondinela", "comuna_id": 1},
    {"barrio": "Chapinerito Alto y Bajo", "comuna_id": 1},
    {"barrio": "Los Cerezos", "comuna_id": 1},
    {"barrio": "La Campiña", "comuna_id": 1},
    {"barrio": "Catalana", "comuna_id": 1},
    {"barrio": "El Poblado", "comuna_id": 1},
    {"barrio": "Doce de Octubre", "comuna_id": 1},
    {"barrio": "Santa Josefa", "comuna_id": 1},
    {"barrio": "El Recuerdo", "comuna_id": 1},
    {"barrio": "Manaure", "comuna_id": 1},
    {"barrio": "Panorama", "comuna_id": 1},
    {"barrio": "Miami", "comuna_id": 1},
    {"barrio": "Orlando", "comuna_id": 1},
    {"barrio": "Nuevayork", "comuna_id": 1},
    {"barrio": "USA", "comuna_id": 1},
    {"barrio": "Londom", "comuna_id": 1},
    {"barrio": "San Felipe", "comuna_id": 1},
    {"barrio": "El Triunfo", "comuna_id": 1},
    {"barrio": "Caudal", "comuna_id": 1},
    {"barrio": "El Prado", "comuna_id": 1},
    {"barrio": "Virrey", "comuna_id": 1},
    {"barrio": "La Grama", "comuna_id": 1},
    {"barrio": "El Rosal", "comuna_id": 1},
    {"barrio": "Emporio", "comuna_id": 1},
    {"barrio": "Alcázares", "comuna_id": 1},
    {"barrio": "La Esmeralda", "comuna_id": 1},
    {"barrio": "San Pablo", "comuna_id": 1},
    {"barrio": "La Victoria", "comuna_id": 1},
    {"barrio": "Nueva Andalucía", "comuna_id": 2},
    {"barrio": "Centro", "comuna_id": 2},
    {"barrio": "La Salle", "comuna_id": 2},
    {"barrio": "Las Colinas", "comuna_id": 2},
    {"barrio": "Azotea", "comuna_id": 2},
    {"barrio": "San Fernando", "comuna_id": 2},
    {"barrio": "Barzal Alto y Bajo", "comuna_id": 2},
    {"barrio": "Maizaro", "comuna_id": 2},
    {"barrio": "Villaflores", "comuna_id": 2},
    {"barrio": "Siete de Agosto", "comuna_id": 2},
    {"barrio": "Buque", "comuna_id": 2},
    {"barrio": "Trapiche", "comuna_id": 2},
    {"barrio": "Villa María", "comuna_id": 2},
    {"barrio": "Villacentro", "comuna_id": 2},
    {"barrio": "Camoa", "comuna_id": 2},
    {"barrio": "Balatá", "comuna_id": 2},
    {"barrio": "Los Pinos", "comuna_id": 2},
    {"barrio": "Bonanza", "comuna_id": 2},
    {"barrio": "Villa Codem", "comuna_id": 2},
    {"barrio": "La Isla", "comuna_id": 2},
    {"barrio": "San José", "comuna_id": 2},
    {"barrio": "Balcones de Toledo", "comuna_id": 2},
    {"barrio": "Sansoucí", "comuna_id": 2},
    {"barrio": "Libertadores", "comuna_id": 2},
    {"barrio": "Pozo Veinte", "comuna_id": 2},
    {"barrio": "Venecia", "comuna_id": 2},
    {"barrio": "Alta Gracia", "comuna_id": 2},
    {"barrio": "Torres de San Juan", "comuna_id": 2},
    {"barrio": "Guayabal", "comuna_id": 3},
    {"barrio": "Santa Fe", "comuna_id": 3},
    {"barrio": "Brisas del Guatiquia", "comuna_id": 3},
    {"barrio": "Las Delicias", "comuna_id": 3},
    {"barrio": "Villa Julia", "comuna_id": 3},
    {"barrio": "San Isidro", "comuna_id": 3},
    {"barrio": "Santa Inés", "comuna_id": 3},
    {"barrio": "El Porvenir", "comuna_id": 3},
    {"barrio": "San Gregorio", "comuna_id": 3},
    {"barrio": "Gaitán", "comuna_id": 3},
    {"barrio": "Veinte de Julio", "comuna_id": 3},
    {"barrio": "Las Ferias", "comuna_id": 3},
    {"barrio": "Antonio Ricaurte", "comuna_id": 3},
    {"barrio": "Industrial", "comuna_id": 3},
    {"barrio": "La Vainilla", "comuna_id": 3},
    {"barrio": "Santander", "comuna_id": 3},
    {"barrio": "La Lambada", "comuna_id": 3},
    {"barrio": "Villa Suárez", "comuna_id": 4},
    {"barrio": "El Paraíso", "comuna_id": 4},
    {"barrio": "Florencia", "comuna_id": 4},
    {"barrio": "El Manantial", "comuna_id": 4},
    {"barrio": "La Ceiba", "comuna_id": 4},
    {"barrio": "Jordán", "comuna_id": 4},
    {"barrio": "Santa Helena", "comuna_id": 4},
    {"barrio": "El Bambú", "comuna_id": 4},
    {"barrio": "Madrigal", "comuna_id": 4},
    {"barrio": "La Bastilla", "comuna_id": 4},
    {"barrio": "Seis de Abril", "comuna_id": 4},
    {"barrio": "Urbanización El Consuelo", "comuna_id": 4},
    {"barrio": "Santa Catalina", "comuna_id": 4},
    {"barrio": "Antonio Villavicencio", "comuna_id": 4},
    {"barrio": "Urbanización El Morichal", "comuna_id": 4},
    {"barrio": "San Luis", "comuna_id": 4},
    {"barrio": "El Recreo", "comuna_id": 4},
    {"barrio": "La Desmotadora", "comuna_id": 4},
    {"barrio": "Prados de Siberia", "comuna_id": 4},
    {"barrio": "Cedritos", "comuna_id": 4},
    {"barrio": "Bosques de Abajam", "comuna_id": 4},
    {"barrio": "Covisán", "comuna_id": 4},
    {"barrio": "Canaán", "comuna_id": 4},
    {"barrio": "Calamar", "comuna_id": 4},
    {"barrio": "El Cedral", "comuna_id": 4},
    {"barrio": "Los Girasoles", "comuna_id": 4},
    {"barrio": "Nueva Colombia 1 y 2", "comuna_id": 4},
    {"barrio": "Portales del Llano", "comuna_id": 4},
    {"barrio": "Villa Fabiola", "comuna_id": 4},
    {"barrio": "El Milagro", "comuna_id": 4},
    {"barrio": "La Gaitana", "comuna_id": 4},
    {"barrio": "Rosales", "comuna_id": 4},
    {"barrio": "Pontevedra", "comuna_id": 4},
    {"barrio": "San Felipe", "comuna_id": 4},
    {"barrio": "San Carlos", "comuna_id": 4},
    {"barrio": "El Rodeo", "comuna_id": 4},
    {"barrio": "Villa Encanto", "comuna_id": 4},
    {"barrio": "Marco A. Pinilla", "comuna_id": 4},
    {"barrio": "Los Maracos", "comuna_id": 4},
    {"barrio": "Ciudad Salitre", "comuna_id": 4},
    {"barrio": "Los Caracoles", "comuna_id": 4},
    {"barrio": "Camino Real", "comuna_id": 4},
    {"barrio": "Parques de Castilla", "comuna_id": 4},
    {"barrio": "Urbanización La Esmeralda", "comuna_id": 4},
    {"barrio": "Popular", "comuna_id": 5},
    {"barrio": "Dos Mil", "comuna_id": 5},
    {"barrio": "Olímpico", "comuna_id": 5},
    {"barrio": "Villa Ortiz", "comuna_id": 5},
    {"barrio": "Camelias", "comuna_id": 5},
    {"barrio": "Cataluña", "comuna_id": 5},
    {"barrio": "Bello Horizonte", "comuna_id": 5},
    {"barrio": "Cantarrana", "comuna_id": 5},
    {"barrio": "Nueva Floresta", "comuna_id": 5},
    {"barrio": "Estero", "comuna_id": 5},
    {"barrio": "Bochica", "comuna_id": 5},
    {"barrio": "Mi Llanura", "comuna_id": 5},
    {"barrio": "Macunaima", "comuna_id": 5},
    {"barrio": "Ariguani", "comuna_id": 5},
    {"barrio": "Vizcaya", "comuna_id": 5},
    {"barrio": "Hacaritama", "comuna_id": 5},
    {"barrio": "Kirpas", "comuna_id": 5},
    {"barrio": "Villa Samper", "comuna_id": 5},
    {"barrio": "Villa Melida", "comuna_id": 5},
    {"barrio": "Ciudadela San Antonio", "comuna_id": 5},
    {"barrio": "El Brillante", "comuna_id": 5},
    {"barrio": "Rincón de Las Marías", "comuna_id": 5},
    {"barrio": "Aguas Claras", "comuna_id": 5},
    {"barrio": "Alameda del Bosque", "comuna_id": 5},
    {"barrio": "Nueva Esperanza", "comuna_id": 5},
    {"barrio": "Sindamanoy", "comuna_id": 5},
    {"barrio": "Cerro Campestre", "comuna_id": 5},
    {"barrio": "Toscana", "comuna_id": 5},
    {"barrio": "Villa Alcaraván", "comuna_id": 5},
    {"barrio": "Altos de Morelia", "comuna_id": 5},
    {"barrio": "Danubio", "comuna_id": 5},
    {"barrio": "Doña Luz", "comuna_id": 5},
    {"barrio": "Remanso", "comuna_id": 5},
    {"barrio": "Menegua", "comuna_id": 5},
    {"barrio": "Buenos Aires", "comuna_id": 5},
    {"barrio": "La Reliquia", "comuna_id": 5},
    {"barrio": "Trece de Mayo", "comuna_id": 5},
    {"barrio": "Gaviotas", "comuna_id": 5},
    {"barrio": "Pacandé", "comuna_id": 5},
    {"barrio": "La Rosita", "comuna_id": 5},
    {"barrio": "Pastrana", "comuna_id": 6},
    {"barrio": "Vainilla", "comuna_id": 6},
    {"barrio": "Veinte de Julio", "comuna_id": 6},
    {"barrio": "Caney", "comuna_id": 6},
    {"barrio": "Simón Bolívar", "comuna_id": 6},
    {"barrio": "Macarena", "comuna_id": 6},
    {"barrio": "Retiro", "comuna_id": 6},
    {"barrio": "Amaral", "comuna_id": 6},
    {"barrio": "Canaima", "comuna_id": 6},
    {"barrio": "Nuevo Maizaro", "comuna_id": 6},
    {"barrio": "Catatumbo", "comuna_id": 6},
    {"barrio": "Nogal", "comuna_id": 6},
    {"barrio": "San Benito", "comuna_id": 6},
    {"barrio": "Guatiquia", "comuna_id": 6},
    {"barrio": "Florida", "comuna_id": 6},
    {"barrio": "Canta Rana", "comuna_id": 6},
    {"barrio": "Nuevo Ricaurte", "comuna_id": 6},
    {"barrio": "El Embudo", "comuna_id": 6},
    {"barrio": "Marsella", "comuna_id": 6},
    {"barrio": "Henry García Bohórquez", "comuna_id": 6},
    {"barrio": "San Francisco", "comuna_id": 6},
    {"barrio": "Brisas del Caney", "comuna_id": 6},
    {"barrio": "Sausalito", "comuna_id": 6},
    {"barrio": "La Esperanza", "comuna_id": 7},
    {"barrio": "Paraíso", "comuna_id": 7},
    {"barrio": "Cooperativo", "comuna_id": 7},
    {"barrio": "Jardín", "comuna_id": 7},
    {"barrio": "Cambulos", "comuna_id": 7},
    {"barrio": "La Serranía", "comuna_id": 7},
    {"barrio": "La Vega", "comuna_id": 7},
    {"barrio": "La Coralina", "comuna_id": 7},
    {"barrio": "Comuneros", "comuna_id": 7},
    {"barrio": "La Alborada", "comuna_id": 7},
    {"barrio": "Villa Bolívar", "comuna_id": 7},
    {"barrio": "Rosa Blanca", "comuna_id": 7},
    {"barrio": "Villa Humberto", "comuna_id": 7},
    {"barrio": "Palmar", "comuna_id": 7},
    {"barrio": "Santa Marta", "comuna_id": 7},
    {"barrio": "Los Centauros", "comuna_id": 7},
    {"barrio": "La Rosita", "comuna_id": 7},
    {"barrio": "Villa Claudia", "comuna_id": 7},
    {"barrio": "Sesquicentenario", "comuna_id": 7},
    {"barrio": "Las Acacias", "comuna_id": 7},
    {"barrio": "Piamonte", "comuna_id": 7},
    {"barrio": "Rosa Linda", "comuna_id": 7},
    {"barrio": "Plena Vida", "comuna_id": 7},
    {"barrio": "Esperanza 2001", "comuna_id": 7},
    {"barrio": "Balmoral", "comuna_id": 7},
    {"barrio": "Los Cerezos", "comuna_id": 7},
    {"barrio": "Villa Hermosa", "comuna_id": 7},
    {"barrio": "Multifamiliares Los Centauros", "comuna_id": 7},
    {"barrio": "Remansos de Rosablanca", "comuna_id": 7},
    {"barrio": "Bosques de Rosablanca", "comuna_id": 7},
    {"barrio": "CASIBARE", "comuna_id": 7},
    {"barrio": "Urbanización Araguaney", "comuna_id": 8},
    {"barrio": "Porfia", "comuna_id": 8},
    {"barrio": "Las Américas", "comuna_id": 8},
    {"barrio": "Playa Rica", "comuna_id": 8},
    {"barrio": "Catumare", "comuna_id": 8},
    {"barrio": "Rincón de las Margaritas", "comuna_id": 8},
    {"barrio": "Guatape", "comuna_id": 8},
    {"barrio": "Álamos sur", "comuna_id": 8},
    {"barrio": "Álamos", "comuna_id": 8},
    {"barrio": "Santa Rosa", "comuna_id": 8},
    {"barrio": "Montecarlo Alto", "comuna_id": 8},
    {"barrio": "La Rochela", "comuna_id": 8},
    {"barrio": "Villa Marina", "comuna_id": 8},
    {"barrio": "La Florida", "comuna_id": 8},
    {"barrio": "Villa Carola", "comuna_id": 8},
    {"barrio": "Villa Lorena", "comuna_id": 8},
    {"barrio": "El Refugio", "comuna_id": 8},
    {"barrio": "Guaicáramo", "comuna_id": 8},
    {"barrio": "San Jorge", "comuna_id": 8},
    {"barrio": "Villa del Río 1", "comuna_id": 8},
    {"barrio": "Villa del Río 2", "comuna_id": 8},
    {"barrio": "Caminos de Montecarlo", "comuna_id": 8},
    {"barrio": "La Nora", "comuna_id": 8},
    {"barrio": "Nueva Jerusalén", "comuna_id": 8},
    {"barrio": "Villa Oriente", "comuna_id": 8},
    {"barrio": "León XIII", "comuna_id": 8},
    {"barrio": "Llano Lindo", "comuna_id": 8},
    {"barrio": "Teusaquillo", "comuna_id": 8},
    {"barrio": "Los Héroes", "comuna_id": 8},
    {"barrio": "Semillas de Paz", "comuna_id": 8},
    {"barrio": "Villa Juliana", "comuna_id": 8},
    {"barrio": "Samán de la Rivera", "comuna_id": 8},
    {"barrio": "Darién", "comuna_id": 8},
    {"barrio": "Brasilia", "comuna_id": 8},
    {"barrio": "La Madrid", "comuna_id": 8},
    {"barrio": "Pinares de Oriente", "comuna_id": 8},
    {"barrio": "Los Guayabos", "comuna_id": 8},
    {"barrio": "La Maporita", "comuna_id": 8},
    {"barrio": "Vilas del Carmen", "comuna_id": 8},
    {"barrio": "Villas de San Agustín", "comuna_id": 8},
    {"barrio": "San Cipriano", "comuna_id": 8},
    {"barrio": "Villas del Ocoa", "comuna_id": 8},
    {"barrio": "Bahía de Playa Rica", "comuna_id": 8},
    {"barrio": "Loma Linda", "comuna_id": 8},
    {"barrio": "Loma Azul", "comuna_id": 8},
    {"barrio": "Palmar de Catumare", "comuna_id": 8},
    {"barrio": "Maranatha", "comuna_id": 8},
    {"barrio": "Villas del Alcaraván", "comuna_id": 8},
    {"barrio": "La Playita", "comuna_id": 8},
    {"barrio": "Los Cambulos", "comuna_id": 8},
    {"barrio": "La Pradera", "comuna_id": 8},
    {"barrio": "Los Guaduales", "comuna_id": 8},
    {"barrio": "El Ruby", "comuna_id": 8},
    {"barrio": "Nuevo Amanecer", "comuna_id": 8},
    {"barrio": "Santa Librada", "comuna_id": 8},
    {"barrio": "Ciudad Cofrem", "comuna_id": 8},
    {"barrio": "La Nueva Fundación", "comuna_id": 8},
    {"barrio": "Villa Sonia", "comuna_id": 8},
    {"barrio": "Villa Marina", "comuna_id": 8},
    {"barrio": "Villa Milena", "comuna_id": 8},
    {"barrio": "Sector de Montecarlo", "comuna_id": 8},
    {"barrio": "Urbanización Divino Niño", "comuna_id": 8},
    {"barrio": "Charrascal", "comuna_id": 8},
    {"barrio": "Ciudad Porfia", "comuna_id": 9},
    {"barrio": "Darién", "comuna_id": 9},
    {"barrio": "Sector la Playa de ciudad Porfía", "comuna_id": 9},
    {"barrio": "Pinares de Oriente", "comuna_id": 9},
    {"barrio": "Alcaraván", "comuna_id": 9},
    {"barrio": "Maporita", "comuna_id": 9},
    {"barrio": "Rincón de las Lomas", "comuna_id": 9},
    {"barrio": "Villas del Ocoa", "comuna_id": 9},
    {"barrio": "Gramalote", "comuna_id": 9},
    {"barrio": "Hábitat", "comuna_id": 9},
    {"barrio": "Charrascal", "comuna_id": 9},
    {"barrio": "Balcones de Brasilia", "comuna_id": 9},
    {"barrio": "Saman de la Rivera", "comuna_id": 9},
    {"barrio": "Ciudad Jardin", "comuna_id": 9},
    {"barrio": "Piedemonte", "comuna_id": 9},
    {"barrio": "Villa Juliana", "comuna_id": 9},
    {"barrio": "Madrid", "comuna_id": 9},
    {"barrio": "Villas del Lago", "comuna_id": 9},
    {"barrio": "Ciudad Porfia Subnormal", "comuna_id": 9},
    {"barrio": "San Agustín", "comuna_id": 9},
    {"barrio": "San Cipriano", "comuna_id": 9},
    {"barrio": "Villa de Paz", "comuna_id": 9},
    {"barrio": "Villas del Alcaravan", "comuna_id": 9},
    {"barrio": "Bosques de la Rivera", "comuna_id": 9},
    {"barrio": "Miramar", "comuna_id": 9},
    {"barrio": "La Aldea", "comuna_id": 9},
    {"barrio": "San Bernardino", "comuna_id": 9},
    {"barrio": "Riviera", "comuna_id": 9},
    {"barrio": "Camelia I", "comuna_id": 9},
    {"barrio": "Cucharón", "comuna_id": 9},
    {"barrio": "Brisas del Ocoa", "comuna_id": 9},
    {"barrio": "Atlántida", "comuna_id": 9},
    {"barrio": "Mariana", "comuna_id": 9},
    {"barrio": "Camelia III", "comuna_id": 9},
    {"barrio": "Camelia IV", "comuna_id": 9},
    {"barrio": "Cambulos", "comuna_id": 9}
]
        }

        ';

        $dataArray = json_decode($data, true);

        foreach ($dataArray['array'] as $Data) {
            DB::table('neighborhood')->insert([
                'uuid'=> Str::uuid(),
                'name' => $Data['barrio'],
                'district_id' => $Data['comuna_id'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}