<?php

namespace Database\Seeders\public_seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HealthTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = '
        {
            "array": [
              {
                "idEntities": "1",
                "emergencyPatients": "12",
                "emergencyBedsAvailable": 5,
                "availableOperatingRooms": 6,
                "intensiveCareUnitAvailable": 2,
                "firstLevelBeds": 5,
                "secondLevelBeds": 6,
                "thirdLevelBeds": 10,
                "bloodBank": true,
                "doctorsInTheShift": 9,
                "nursesInTheShift": 2,
                "affiliatedIps": "Sanitas",
                "numberOfEmergenciesDay": 15
              },
              {
                "idEntities": "2",
                "emergencyPatients": "4",
                "emergencyBedsAvailable": 7,
                "availableOperatingRooms": 9,
                "intensiveCareUnitAvailable": 6,
                "firstLevelBeds": 4,
                "secondLevelBeds": 6,
                "thirdLevelBeds": 5,
                "bloodBank": true,
                "doctorsInTheShift": 12,
                "nursesInTheShift": 32,
                "affiliatedIps": "Medical",
                "numberOfEmergenciesDay": 59
              },
              {
                "idEntities": "3",
                "emergencyPatients": "17",
                "emergencyBedsAvailable": 8,
                "availableOperatingRooms": 4,
                "intensiveCareUnitAvailable": 1,
                "firstLevelBeds": 8,
                "secondLevelBeds": 12,
                "thirdLevelBeds": 3,
                "bloodBank": false,
                "doctorsInTheShift": 7,
                "nursesInTheShift": 20,
                "affiliatedIps": "HealthCare",
                "numberOfEmergenciesDay": 25
              },
              {
                "idEntities": "4",
                "emergencyPatients": "8",
                "emergencyBedsAvailable": 3,
                "availableOperatingRooms": 11,
                "intensiveCareUnitAvailable": 4,
                "firstLevelBeds": 3,
                "secondLevelBeds": 2,
                "thirdLevelBeds": 8,
                "bloodBank": true,
                "doctorsInTheShift": 5,
                "nursesInTheShift": 10,
                "affiliatedIps": "MediCare",
                "numberOfEmergenciesDay": 10
              },
              {
                "idEntities": "5",
                "emergencyPatients": "20",
                "emergencyBedsAvailable": 10,
                "availableOperatingRooms": 3,
                "intensiveCareUnitAvailable": 3,
                "firstLevelBeds": 15,
                "secondLevelBeds": 10,
                "thirdLevelBeds": 5,
                "bloodBank": true,
                "doctorsInTheShift": 8,
                "nursesInTheShift": 12,
                "affiliatedIps": "HealthPro",
                "numberOfEmergenciesDay": 30
              },
              {
                "idEntities": "6",
                "emergencyPatients": "5",
                "emergencyBedsAvailable": 2,
                "availableOperatingRooms": 8,
                "intensiveCareUnitAvailable": 5,
                "firstLevelBeds": 6,
                "secondLevelBeds": 7,
                "thirdLevelBeds": 4,
                "bloodBank": true,
                "doctorsInTheShift": 10,
                "nursesInTheShift": 15,
                "affiliatedIps": "MediHealth",
                "numberOfEmergenciesDay": 12
              },
              {
                "idEntities": "7",
                "emergencyPatients": "13",
                "emergencyBedsAvailable": 6,
                "availableOperatingRooms": 10,
                "intensiveCareUnitAvailable": 7,
                "firstLevelBeds": 8,
                "secondLevelBeds": 8,
                "thirdLevelBeds": 9,
                "bloodBank": false,
                "doctorsInTheShift": 14,
                "nursesInTheShift": 28,
                "affiliatedIps": "LifeCare",
                "numberOfEmergenciesDay": 20
              },
              {
                "idEntities": "8",
                "emergencyPatients": "9",
                "emergencyBedsAvailable": 4,
                "availableOperatingRooms": 5,
                "intensiveCareUnitAvailable": 2,
                "firstLevelBeds": 5,
                "secondLevelBeds": 4,
                "thirdLevelBeds": 6,
                "bloodBank": true,
                "doctorsInTheShift": 6,
                "nursesInTheShift": 10,
                "affiliatedIps": "MedConnect",
                "numberOfEmergenciesDay": 9
              },
              {
                "idEntities": "9",
                "emergencyPatients": "6",
                "emergencyBedsAvailable": 3,
                "availableOperatingRooms": 7,
                "intensiveCareUnitAvailable": 1,
                "firstLevelBeds": 4,
                "secondLevelBeds": 5,
                "thirdLevelBeds": 3,
                "bloodBank": false,
                "doctorsInTheShift": 8,
                "nursesInTheShift": 14,
                "affiliatedIps": "MediPro",
                "numberOfEmergenciesDay": 8
              },
              {
                "idEntities": "10",
                "emergencyPatients": "10",
                "emergencyBedsAvailable": 4,
                "availableOperatingRooms": 6,
                "intensiveCareUnitAvailable": 3,
                "firstLevelBeds": 7,
                "secondLevelBeds": 8,
                "thirdLevelBeds": 5,
                "bloodBank": true,
                "doctorsInTheShift": 9,
                "nursesInTheShift": 18,
                "affiliatedIps": "HealthPlus",
                "numberOfEmergenciesDay": 18
              },
              {
                "idEntities": "11",
                "emergencyPatients": "19",
                "emergencyBedsAvailable": 9,
                "availableOperatingRooms": 5,
                "intensiveCareUnitAvailable": 2,
                "firstLevelBeds": 6,
                "secondLevelBeds": 10,
                "thirdLevelBeds": 8,
                "bloodBank": true,
                "doctorsInTheShift": 11,
                "nursesInTheShift": 22,
                "affiliatedIps": "MediAssist",
                "numberOfEmergenciesDay": 27
              },
              {
                "idEntities": "12",
                "emergencyPatients": "7",
                "emergencyBedsAvailable": 2,
                "availableOperatingRooms": 4,
                "intensiveCareUnitAvailable": 1,
                "firstLevelBeds": 3,
                "secondLevelBeds": 5,
                "thirdLevelBeds": 2,
                "bloodBank": false,
                "doctorsInTheShift": 5,
                "nursesInTheShift": 10,
                "affiliatedIps": "MedLife",
                "numberOfEmergenciesDay": 11
              },
              {
                "idEntities": "13",
                "emergencyPatients": "15",
                "emergencyBedsAvailable": 6,
                "availableOperatingRooms": 9,
                "intensiveCareUnitAvailable": 4,
                "firstLevelBeds": 8,
                "secondLevelBeds": 12,
                "thirdLevelBeds": 6,
                "bloodBank": true,
                "doctorsInTheShift": 13,
                "nursesInTheShift": 25,
                "affiliatedIps": "HealthCare",
                "numberOfEmergenciesDay": 22
              },
              {
                "idEntities": "14",
                "emergencyPatients": "3",
                "emergencyBedsAvailable": 1,
                "availableOperatingRooms": 7,
                "intensiveCareUnitAvailable": 3,
                "firstLevelBeds": 5,
                "secondLevelBeds": 6,
                "thirdLevelBeds": 4,
                "bloodBank": true,
                "doctorsInTheShift": 7,
                "nursesInTheShift": 15,
                "affiliatedIps": "MedConnect",
                "numberOfEmergenciesDay": 7
              },
              {
                "idEntities": "15",
                "emergencyPatients": "11",
                "emergencyBedsAvailable": 4,
                "availableOperatingRooms": 8,
                "intensiveCareUnitAvailable": 3,
                "firstLevelBeds": 6,
                "secondLevelBeds": 7,
                "thirdLevelBeds": 5,
                "bloodBank": false,
                "doctorsInTheShift": 9,
                "nursesInTheShift": 17,
                "affiliatedIps": "MediPro",
                "numberOfEmergenciesDay": 14
              },
              {
                "idEntities": "16",
                "emergencyPatients": "9",
                "emergencyBedsAvailable": 3,
                "availableOperatingRooms": 10,
                "intensiveCareUnitAvailable": 2,
                "firstLevelBeds": 4,
                "secondLevelBeds": 5,
                "thirdLevelBeds": 3,
                "bloodBank": true,
                "doctorsInTheShift": 8,
                "nursesInTheShift": 15,
                "affiliatedIps": "LifeCare",
                "numberOfEmergenciesDay": 12
              },
              {
                "idEntities": "17",
                "emergencyPatients": "6",
                "emergencyBedsAvailable": 2,
                "availableOperatingRooms": 5,
                "intensiveCareUnitAvailable": 1,
                "firstLevelBeds": 3,
                "secondLevelBeds": 3,
                "thirdLevelBeds": 2,
                "bloodBank": true,
                "doctorsInTheShift": 4,
                "nursesInTheShift": 9,
                "affiliatedIps": "HealthPlus",
                "numberOfEmergenciesDay": 6
              },
              {
                "idEntities": "18",
                "emergencyPatients": "14",
                "emergencyBedsAvailable": 7,
                "availableOperatingRooms": 4,
                "intensiveCareUnitAvailable": 3,
                "firstLevelBeds": 5,
                "secondLevelBeds": 8,
                "thirdLevelBeds": 5,
                "bloodBank": false,
                "doctorsInTheShift": 10,
                "nursesInTheShift": 20,
                "affiliatedIps": "MediLife",
                "numberOfEmergenciesDay": 20
              },
              {
                "idEntities": "19",
                "emergencyPatients": "8",
                "emergencyBedsAvailable": 4,
                "availableOperatingRooms": 6,
                "intensiveCareUnitAvailable": 2,
                "firstLevelBeds": 6,
                "secondLevelBeds": 6,
                "thirdLevelBeds": 4,
                "bloodBank": true,
                "doctorsInTheShift": 7,
                "nursesInTheShift": 12,
                "affiliatedIps": "MediAssist",
                "numberOfEmergenciesDay": 10
              },
              {
                "idEntities": "20",
                "emergencyPatients": "12",
                "emergencyBedsAvailable": 5,
                "availableOperatingRooms": 9,
                "intensiveCareUnitAvailable": 5,
                "firstLevelBeds": 6,
                "secondLevelBeds": 8,
                "thirdLevelBeds": 6,
                "bloodBank": true,
                "doctorsInTheShift": 11,
                "nursesInTheShift": 20,
                "affiliatedIps": "HealthPro",
                "numberOfEmergenciesDay": 18
              },
              {
                "idEntities": "21",
                "emergencyPatients": "18",
                "emergencyBedsAvailable": 8,
                "availableOperatingRooms": 7,
                "intensiveCareUnitAvailable": 4,
                "firstLevelBeds": 7,
                "secondLevelBeds": 10,
                "thirdLevelBeds": 6,
                "bloodBank": true,
                "doctorsInTheShift": 12,
                "nursesInTheShift": 25,
                "affiliatedIps": "MedConnect",
                "numberOfEmergenciesDay": 25
              },
              {
                "idEntities": "22",
                "emergencyPatients": "5",
                "emergencyBedsAvailable": 3,
                "availableOperatingRooms": 6,
                "intensiveCareUnitAvailable": 3,
                "firstLevelBeds": 5,
                "secondLevelBeds": 6,
                "thirdLevelBeds": 3,
                "bloodBank": true,
                "doctorsInTheShift": 8,
                "nursesInTheShift": 15,
                "affiliatedIps": "HealthCare",
                "numberOfEmergenciesDay": 13
              },
              {
                "idEntities": "23",
                "emergencyPatients": "3",
                "emergencyBedsAvailable": 1,
                "availableOperatingRooms": 4,
                "intensiveCareUnitAvailable": 2,
                "firstLevelBeds": 3,
                "secondLevelBeds": 4,
                "thirdLevelBeds": 2,
                "bloodBank": false,
                "doctorsInTheShift": 5,
                "nursesInTheShift": 9,
                "affiliatedIps": "MediPro",
                "numberOfEmergenciesDay": 6
              },
              {
                "idEntities": "24",
                "emergencyPatients": "15",
                "emergencyBedsAvailable": 6,
                "availableOperatingRooms": 8,
                "intensiveCareUnitAvailable": 3,
                "firstLevelBeds": 7,
                "secondLevelBeds": 7,
                "thirdLevelBeds": 4,
                "bloodBank": true,
                "doctorsInTheShift": 10,
                "nursesInTheShift": 18,
                "affiliatedIps": "LifeCare",
                "numberOfEmergenciesDay": 21
              },
              {
                "idEntities": "25",
                "emergencyPatients": "7",
                "emergencyBedsAvailable": 2,
                "availableOperatingRooms": 6,
                "intensiveCareUnitAvailable": 1,
                "firstLevelBeds": 4,
                "secondLevelBeds": 4,
                "thirdLevelBeds": 3,
                "bloodBank": true,
                "doctorsInTheShift": 6,
                "nursesInTheShift": 11,
                "affiliatedIps": "HealthPlus",
                "numberOfEmergenciesDay": 9
              },
              {
                "idEntities": "26",
                "emergencyPatients": "10",
                "emergencyBedsAvailable": 5,
                "availableOperatingRooms": 9,
                "intensiveCareUnitAvailable": 2,
                "firstLevelBeds": 6,
                "secondLevelBeds": 8,
                "thirdLevelBeds": 4,
                "bloodBank": false,
                "doctorsInTheShift": 9,
                "nursesInTheShift": 17,
                "affiliatedIps": "MediAssist",
                "numberOfEmergenciesDay": 14
              },
              {
                "idEntities": "27",
                "emergencyPatients": "9",
                "emergencyBedsAvailable": 4,
                "availableOperatingRooms": 7,
                "intensiveCareUnitAvailable": 3,
                "firstLevelBeds": 5,
                "secondLevelBeds": 6,
                "thirdLevelBeds": 4,
                "bloodBank": true,
                "doctorsInTheShift": 8,
                "nursesInTheShift": 16,
                "affiliatedIps": "MediLife",
                "numberOfEmergenciesDay": 12
              },
              {
                "idEntities": "28",
                "emergencyPatients": "6",
                "emergencyBedsAvailable": 3,
                "availableOperatingRooms": 5,
                "intensiveCareUnitAvailable": 2,
                "firstLevelBeds": 4,
                "secondLevelBeds": 4,
                "thirdLevelBeds": 3,
                "bloodBank": true,
                "doctorsInTheShift": 6,
                "nursesInTheShift": 11,
                "affiliatedIps": "HealthPro",
                "numberOfEmergenciesDay": 9
              },
              {
                "idEntities": "29",
                "emergencyPatients": "11",
                "emergencyBedsAvailable": 5,
                "availableOperatingRooms": 9,
                "intensiveCareUnitAvailable": 3,
                "firstLevelBeds": 7,
                "secondLevelBeds": 7,
                "thirdLevelBeds": 5,
                "bloodBank": true,
                "doctorsInTheShift": 10,
                "nursesInTheShift": 19,
                "affiliatedIps": "MedConnect",
                "numberOfEmergenciesDay": 17
              },
              {
                "idEntities": "30",
                "emergencyPatients": "18",
                "emergencyBedsAvailable": 8,
                "availableOperatingRooms": 7,
                "intensiveCareUnitAvailable": 4,
                "firstLevelBeds": 8,
                "secondLevelBeds": 10,
                "thirdLevelBeds": 6,
                "bloodBank": false,
                "doctorsInTheShift": 12,
                "nursesInTheShift": 24,
                "affiliatedIps": "MediAssist",
                "numberOfEmergenciesDay": 23
              },
              {
                "idEntities": "31",
                "emergencyPatients": "5",
                "emergencyBedsAvailable": 3,
                "availableOperatingRooms": 6,
                "intensiveCareUnitAvailable": 3,
                "firstLevelBeds": 5,
                "secondLevelBeds": 7,
                "thirdLevelBeds": 3,
                "bloodBank": true,
                "doctorsInTheShift": 8,
                "nursesInTheShift": 16,
                "affiliatedIps": "HealthPro",
                "numberOfEmergenciesDay": 11
              },
              {
                "idEntities": "32",
                "emergencyPatients": "12",
                "emergencyBedsAvailable": 6,
                "availableOperatingRooms": 8,
                "intensiveCareUnitAvailable": 2,
                "firstLevelBeds": 6,
                "secondLevelBeds": 8,
                "thirdLevelBeds": 5,
                "bloodBank": false,
                "doctorsInTheShift": 9,
                "nursesInTheShift": 18,
                "affiliatedIps": "MedConnect",
                "numberOfEmergenciesDay": 16
              },
              {
                "idEntities": "33",
                "emergencyPatients": "14",
                "emergencyBedsAvailable": 7,
                "availableOperatingRooms": 9,
                "intensiveCareUnitAvailable": 4,
                "firstLevelBeds": 7,
                "secondLevelBeds": 9,
                "thirdLevelBeds": 6,
                "bloodBank": true,
                "doctorsInTheShift": 11,
                "nursesInTheShift": 21,
                "affiliatedIps": "HealthCare",
                "numberOfEmergenciesDay": 20
              }
            ]
          }
          
          ';

        $dataArray = json_decode($data, true);

        foreach ($dataArray['array'] as $Data) {
            DB::table('health')->insert([
                'idEntities' => $Data['idEntities'],
                'emergencyPatients' => $Data['emergencyPatients'],
                'emergencyBedsAvailable' => $Data['emergencyBedsAvailable'],
                'availableOperatingRooms' => $Data['availableOperatingRooms'],
                'intensiveCareUnitAvailable' => $Data['intensiveCareUnitAvailable'],
                'firstLevelBeds' => $Data['firstLevelBeds'],
                'secondLevelBeds' => $Data['secondLevelBeds'],
                'thirdLevelBeds' => $Data['thirdLevelBeds'],
                'bloodBank' => $Data['bloodBank'],
                'doctorsInTheShift' => $Data['doctorsInTheShift'],
                'nursesInTheShift' => $Data['nursesInTheShift'],
                'affiliatedIps' => $Data['affiliatedIps'],
                'numberOfEmergenciesDay' => $Data['numberOfEmergenciesDay'],
            ]);
        }
    }
}
